Repository jupyterlab/jupyter-ai, pull requests merged in 2023-12, with the labels that each got.

#494 Update Users section of the docs
  docs/source/_static/chat-getting-started.png
  docs/source/_static/chat-select-model-complete.png
  docs/source/_static/chat-select-model.png
  docs/source/_static/chat-settings-choose-language-model.png
  docs/source/developers/index.md
  docs/source/users/index.md
Labels: documentation

#503 Remove config.json-related information
  docs/source/users/index.md
Labels: documentation

#398 Base chat handler refactor for custom slash commands
  docs/source/developers/index.md
  packages/jupyter-ai/jupyter_ai/chat_handlers/__init__.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/clear.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
Labels: enhancement, @jupyter-ai/chatui

#517 Update README.md - under incubation
  README.md
Labels: documentation, enhancement

#490 Respect user preferred dir and allow to configure logs dir
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: enhancement

#519 Run unit tests as a part of CI
  .github/workflows/unit-tests.yml
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
Labels: enhancement, maintenance, testing

#523 Backport PR #519 on branch 1.x (Run Python unit tests as a part of CI)
  .github/workflows/unit-tests.yml
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
Labels: enhancement, maintenance, testing

#522 Upgrades to langchain 0.0.350
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/pyproject.toml
Labels: enhancement, maintenance, @jupyter-ai/core

#524 Backport PR #522 on branch 1.x (Upgrades to langchain 0.0.350)
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/pyproject.toml
Labels: enhancement, maintenance, @jupyter-ai/core

#520 Dynamically generate help message for slash commands in chat UI
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/clear.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: enhancement

#526 Backport PR #520 on branch 1.x (Dynamically generate help message for slash commands in chat UI)
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/clear.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: enhancement

#506 Handle LLMs lacking concurrency support in Chat UI
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/clear.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
Labels: bug, needs-backport

#528 [1.x] Respect user preferred dir and allow to configure logs dir
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: enhancement

#529 Backport PR #506 on branch 1.x (Handle LLMs lacking concurrency support in Chat UI)
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/clear.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
Labels: bug, needs-backport

#513 Make Jupyternaut reply for API auth errors user-friendly
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
Labels: enhancement

#532 Backport PR #513 on branch 1.x (Make Jupyternaut reply for API auth errors user-friendly)
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
Labels: enhancement

#527 Refactor ConfigManager._init_config
  packages/jupyter-ai/jupyter_ai/config_manager.py
Labels: enhancement, maintenance

#534 Backport PR #527 on branch 1.x (Refactor ConfigManager._init_config)
  packages/jupyter-ai/jupyter_ai/config_manager.py
Labels: enhancement, maintenance

#535 Backport PR #517 on branch 1.x (Update README.md - under incubation)
  README.md
Labels: documentation, enhancement

#536 Main branch is compatible with Lab 4 only
  packages/jupyter-ai/README.md
Labels: documentation

#533 Document entry point and API for custom embedding models
  docs/source/developers/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
Labels: documentation

#537 Backport PR #533 on branch 1.x (Document entry point and API for custom embedding models)
  docs/source/developers/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
Labels: documentation

#531 Adds multi-environment variable authentication, Baidu Qianfan ERNIE-bot provider
  .gitignore
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/aliases.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement

#539 Backport PR #531 on branch 1.x (Adds multi-environment variable authentication, Baidu Qianfan ERNIE-bot provider)
  .gitignore
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/aliases.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement

#540 Add gpt-4-1106-preview model from openai
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#545 Backport PR #540 on branch 1.x (Add gpt-4-1106-preview model from openai)
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#546 Validate Pydantic imports
  .github/workflows/lint.yml
  nx.json
  package.json
  packages/jupyter-ai-magics/package.json
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/pyproject.toml
  pyproject.toml
Labels: bug, maintenance

#548 [1.x] Validate Pydantic imports
  .github/workflows/lint.yml
  nx.json
  package.json
  packages/jupyter-ai-magics/package.json
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/pyproject.toml
  pyproject.toml
Labels: bug, maintenance

#547 Clarify/fix conda instructions
  README.md
Labels: documentation

#549 Update README.md for JupyterLab 3 / Jupyter AI 1.x
  README.md
Labels: documentation
