Repository jupyterlab/jupyter-ai, pull requests merged in 2023-11, with the labels that each got.

#429 Rename Bedrock and Bedrock chat providers in docs
  docs/source/users/index.md
Labels: bug, documentation

#427 /learn skips hidden files/dirs by default, unless "-a" is specified
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
Labels: enhancement, @jupyter-ai/chatui

#432 DOC: Render hugging face url as link
  docs/source/users/index.md
Labels: documentation, enhancement

#431 Log exceptions in `/generate` to a file
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/clear.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/handlers.py
Labels: enhancement

#440 [1.x] Log exceptions in `/generate` to a file
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/clear.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/handlers.py
Labels: enhancement

#446 Model allowlist and blocklists
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_extension.py
Labels: enhancement

#430 Model parameters option to pass in model tuning, arbitrary parameters
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: bug, enhancement

#453 Backport PR #430 on branch 1.x (Model parameters option to pass in model tuning, arbitrary parameters)
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: bug, enhancement

#451 Backport PR #427 on branch 1.x (/learn skips hidden files/dirs by default, unless "-a" is specified)
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
Labels: enhancement, @jupyter-ai/chatui

#452 Backport PR #446 on branch 1.x (Model allowlist and blocklists)
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_extension.py
Labels: enhancement

#450 Updated docs for config.
  docs/source/users/index.md
Labels: documentation

#454 Add gpt4all local models, including an embedding provider
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
Labels: bug, enhancement

#457 Add step to create a GPT4All cache folder to the docs
  docs/source/users/index.md
Labels: documentation, enhancement

#461 Backport PR #450 on branch 1.x (Updated docs for config.)
  docs/source/users/index.md
Labels: documentation

#462 Backport PR #454 on branch 1.x (Add gpt4all local models, including an embedding provider)
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
Labels: bug, enhancement

#458 Backport PR #457 on branch 1.x (Add step to create a GPT4All cache folder to the docs)
  docs/source/users/index.md
Labels: documentation, enhancement

#439 Copy edits for Jupyternaut messages
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
Labels: documentation, enhancement

#459 If model_provider_id or embeddings_provider_id is not associated with models, set it to None
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
Labels: bug

#467 Backport PR #459 on branch 1.x (If model_provider_id or embeddings_provider_id is not associated with models, set it to None)
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
Labels: bug

#443 Ensure initials appear in collaborative mode
  packages/jupyter-ai/jupyter_ai/handlers.py
Labels: bug

#466 Pydantic v1 and v2 compatibility
  docs/source/contributors/index.md
  docs/source/developers/index.md
  docs/source/index.md
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/pyproject.toml
Labels: enhancement, @jupyter-ai/core

#471 (1.x) Pydantic v1 and v2 compatibility
  docs/source/contributors/index.md
  docs/source/developers/index.md
  docs/source/index.md
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/pyproject.toml
Labels: enhancement, @jupyter-ai/core

#475 Copy edits for Jupyternaut messages
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
Labels: documentation, enhancement

#474 Make links from Jupyter AI chat open in new tab (vs in the same tab currently)
  packages/jupyter-ai/src/components/chat-messages.tsx
Labels: bug

#473 Update README.md
  README.md
Labels: documentation

#479 Backport PR #473 on branch 1.x (Update README.md)
  README.md
Labels: documentation

#477 Don't run check-release on release
  .github/workflows/check-release.yml
Labels: maintenance

#484 Backport PR #477 on branch 1.x (Don't run check-release on release)
  .github/workflows/check-release.yml
Labels: maintenance

#489 Remove stale `@jupyterlab/collaboration` dependency
  packages/jupyter-ai/package.json
  packages/jupyter-ai/src/components/settings/existing-api-keys.tsx
  yarn.lock
Labels: maintenance
