Repository jupyterlab/jupyter-ai, pull requests merged in 2023-05, with the labels that each got.

#66 Format image provider
  docs/source/users/index.md
  examples/images.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement, @jupyter-ai/magics

#131 Copy edits in README
  README.md
Labels: documentation, enhancement

#132 Additional README copy edits
  README.md
Labels: documentation, enhancement

#125 Revise screen shots in docs
  docs/source/_static/chat-ask-command.png
  docs/source/_static/chat-explain-code-output.png
  docs/source/_static/chat-generate-command-response.png
  docs/source/_static/chat-generate-file.png
  docs/source/_static/chat-generate-input.png
  docs/source/_static/chat-hello-world.png
  docs/source/_static/chat-icon-left-tab-bar.png
  docs/source/_static/chat-learn-delete.png
  docs/source/_static/chat-learn-docs.png
  docs/source/_static/css/custom.css
  docs/source/conf.py
  docs/source/users/index.md
Labels: documentation, enhancement

#134 Pin LangChain version
  packages/jupyter-ai/pyproject.toml
  scripts/bump-version.sh
Labels: bug

#135 [0.6.x] Pin LangChain version
  packages/jupyter-ai/pyproject.toml
  scripts/bump-version.sh
Labels: maintenance

#139 Adds helper text to chat input field
  .github/workflows/check-release.yml
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/components/chat.tsx
Labels: enhancement

#141 Chat settings UI
  packages/jupyter-ai/jupyter_ai/actors/chat_provider.py
  packages/jupyter-ai/jupyter_ai/actors/config.py
  packages/jupyter-ai/jupyter_ai/actors/embeddings_provider.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/select.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement

#144 Various chat chain enhancements and fixes
  .readthedocs.yaml
  packages/jupyter-ai/jupyter_ai/actors/base.py
  packages/jupyter-ai/jupyter_ai/actors/default.py
  packages/jupyter-ai/jupyter_ai/actors/router.py
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: bug, enhancement

#146 Runtime model configurability
  .readthedocs.yaml
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/aliases.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/utils.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/.gitignore
  packages/jupyter-ai/jupyter_ai/actors/ask.py
  packages/jupyter-ai/jupyter_ai/actors/base.py
  packages/jupyter-ai/jupyter_ai/actors/chat_provider.py
  packages/jupyter-ai/jupyter_ai/actors/config.py
  packages/jupyter-ai/jupyter_ai/actors/default.py
  packages/jupyter-ai/jupyter_ai/actors/embeddings_provider.py
  packages/jupyter-ai/jupyter_ai/actors/generate.py
  packages/jupyter-ai/jupyter_ai/actors/learn.py
  packages/jupyter-ai/jupyter_ai/actors/providers.py
  packages/jupyter-ai/jupyter_ai/actors/router.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/select.tsx
  packages/jupyter-ai/src/handler.ts
Labels: bug, enhancement

#145 Update providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/pyproject.toml
Labels: enhancement

#147 Introduce Jupyternaut
  packages/jupyter-ai/jupyter_ai/actors/default.py
  packages/jupyter-ai/jupyter_ai/actors/learn.py
  packages/jupyter-ai/schema/plugin.json
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/icons.ts
  packages/jupyter-ai/style/icons/jupyternaut.svg
  packages/jupyter-ai/style/icons/psychology.svg
Labels: enhancement

#148 Tweak font styles for code blocks in chat
  packages/jupyter-ai/src/components/chat-code-view.tsx
  packages/jupyter-ai/style/react-markdown.css
Labels: enhancement

#149 Updates docs to refer to new setup process
  docs/source/_static/chat-ask-command.png
  docs/source/_static/chat-explain-code-output.png
  docs/source/_static/chat-generate-command-response.png
  docs/source/_static/chat-generate-file.png
  docs/source/_static/chat-generate-input.png
  docs/source/_static/chat-generate-notebook-opened.png
  docs/source/_static/chat-getting-started.png
  docs/source/_static/chat-hello-world.png
  docs/source/_static/chat-icon-left-tab-bar.png
  docs/source/_static/chat-interface-selection.png
  docs/source/_static/chat-learn-delete.png
  docs/source/_static/chat-learn-docs.png
  docs/source/_static/chat-replace-selection-input.png
  docs/source/_static/chat-replace-selection-output.png
  docs/source/_static/chat-select-model-complete.png
  docs/source/_static/chat-select-model.png
  docs/source/users/index.md
Labels: documentation, enhancement

#155 Adds missing newline before closing code block
  packages/jupyter-ai/src/components/chat.tsx
Labels: bug, @jupyter-ai/chatui

#161 Fixes error for config, when new installation is done
  packages/jupyter-ai/jupyter_ai/actors/config.py
Labels: bug

#158 Documents server 2 as a requirement
  docs/source/users/index.md
  packages/jupyter-ai/README.md
Labels: documentation, enhancement

#165 Remove reference to now-nonexistent file
  docs/source/users/index.md
Labels: bug, documentation

#157 Uses React 17, not 18, for @jupyter-ai/core dependency
  packages/jupyter-ai/package.json
  yarn.lock
Labels: bug, @jupyter-ai/core

#154 Chat UI quality of life improvements
  docs/source/_static/chat-icon-left-tab-bar.png
  packages/jupyter-ai/src/components/chat-input.tsx
Labels: enhancement, @jupyter-ai/chatui

#174 Fix `yarn install` in CI
  .github/workflows/check-release.yml
  .jupyter-releaser.toml
  yarn.lock
Labels: bug

#164 Adds config option to use ENTER to send message
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement, @jupyter-ai/chatui

#159 Changes chat messages to use absolute timestamps
  packages/jupyter-ai/package.json
  packages/jupyter-ai/src/components/chat-messages.tsx
  yarn.lock
Labels: enhancement, @jupyter-ai/chatui

#178 fix: Correct recursion error on load in JupyterHub
  packages/jupyter-ai/jupyter_ai/handlers.py
Labels: bug

#185 Additional docs fix for 3.8 support
  docs/source/users/index.md
Labels: documentation, enhancement

#192 SageMaker Studio support
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/actors/default.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/src/theme-provider.ts
Labels: bug

#196 Add documentation for running magics in remote kernels
  docs/source/contributors/index.md
  docs/source/users/index.md
  scripts/install.sh
Labels: documentation

#188 Migrate to click
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement
