Repository jupyterlab/jupyter-ai, pull requests merged in 2023-09, with the labels that each got.

#374 Loads vector store index lazily
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
Labels: enhancement

#379 [1.x] Backport [2.1.0, 2.2.0)
  .gitignore
  README.md
  docs/source/_static/jupyter-ai-screenshot.png
  docs/source/contributors/index.md
  docs/source/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/README.md
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/src/__tests__/jupyter_gai.spec.ts
Labels: bug, documentation, enhancement

#367 jupyter_ai and jupyter_ai_magics version match
  docs/source/users/index.md
Labels: documentation, enhancement

#353 Config V2
  conftest.py
  package.json
  packages/jupyter-ai/.gitignore
  packages/jupyter-ai/jest.config.js
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/config/config_schema.json
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/__snapshots__/test_config_manager.ambr
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/mui-extras/async-icon-button.tsx
  packages/jupyter-ai/src/components/mui-extras/contrasting-tooltip.tsx
  packages/jupyter-ai/src/components/mui-extras/stacking-alert.tsx
  packages/jupyter-ai/src/components/settings/__tests__/chat-settings.spec.ts
  packages/jupyter-ai/src/components/settings/existing-api-keys.tsx
  packages/jupyter-ai/src/components/settings/minify.ts
  packages/jupyter-ai/src/components/settings/model-fields.tsx
  packages/jupyter-ai/src/components/settings/use-server-info.ts
  packages/jupyter-ai/src/components/settings/validator.ts
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/tsconfig.test.json
  yarn.lock
Labels: enhancement

#382 [1.x] Config V2
  conftest.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/config/config_schema.json
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/__snapshots__/test_config_manager.ambr
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/mui-extras/async-icon-button.tsx
  packages/jupyter-ai/src/components/mui-extras/contrasting-tooltip.tsx
  packages/jupyter-ai/src/components/mui-extras/stacking-alert.tsx
  packages/jupyter-ai/src/components/settings/__tests__/chat-settings.spec.ts
  packages/jupyter-ai/src/components/settings/existing-api-keys.tsx
  packages/jupyter-ai/src/components/settings/minify.ts
  packages/jupyter-ai/src/components/settings/model-fields.tsx
  packages/jupyter-ai/src/components/settings/use-server-info.ts
  packages/jupyter-ai/src/components/settings/validator.ts
  packages/jupyter-ai/src/handler.ts
Labels: enhancement

#373 Adds help text for registry model providers in chat UI settings
  examples/commands.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/style/chat-settings.css
Labels: enhancement, @jupyter-ai/chatui

#383 [1.x] Adds help text for registry model providers in chat UI settings (#373)
  examples/commands.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/style/chat-settings.css
Labels: enhancement, @jupyter-ai/chatui

#350 Add E2E tests
  .github/workflows/e2e-tests.yml
  .github/workflows/update-snapshots.yml
  docs/source/contributors/index.md
  packages/jupyter-ai/.gitignore
  packages/jupyter-ai/ui-tests/README.md
  packages/jupyter-ai/ui-tests/jupyter_server_test_config.py
  packages/jupyter-ai/ui-tests/package.json
  packages/jupyter-ai/ui-tests/tests/helpers/AIHelper.ts
  packages/jupyter-ai/ui-tests/tests/jupyter-ai.spec.ts
  packages/jupyter-ai/ui-tests/tests/jupyter-ai.spec.ts-snapshots/chat-welcome-message-linux.png
  packages/jupyter-ai/ui-tests/tests/jupyter-ai.spec.ts-snapshots/sidebar-linux.png
  packages/jupyter-ai/ui-tests/tests/jupyter_ai.spec.ts
  packages/jupyter-ai/ui-tests/yarn.lock
Labels: enhancement, maintenance, testing, project:ui

#388 [1.x] Add E2E tests
  .github/workflows/e2e-tests.yml
  .github/workflows/update-snapshots.yml
  docs/source/contributors/index.md
  packages/jupyter-ai/.gitignore
  packages/jupyter-ai/ui-tests/README.md
  packages/jupyter-ai/ui-tests/package.json
  packages/jupyter-ai/ui-tests/tests/helpers/AIHelper.ts
  packages/jupyter-ai/ui-tests/tests/jupyter-ai.spec.ts
  packages/jupyter-ai/ui-tests/tests/jupyter-ai.spec.ts-snapshots/chat-welcome-message-linux.png
  packages/jupyter-ai/ui-tests/tests/jupyter-ai.spec.ts-snapshots/sidebar-linux.png
  packages/jupyter-ai/ui-tests/tests/jupyter_ai.spec.ts
  packages/jupyter-ai/ui-tests/yarn.lock
Labels: enhancement, maintenance, testing, project:ui

#391 Adds chat anthropic provider, new models
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: bug, enhancement
