Repository jupyterlab/jupyter-ai, pull requests merged in 2023-08, with the labels that each got.

#314 add claude 2 to anthropic models
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#317 Backport #314 to 1.x
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#309 Prompt template override in BaseProvider
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement, @jupyter-ai/magics

#316 handle IDPs that don't return initials
  packages/jupyter-ai/jupyter_ai/handlers.py
Labels: bug, backport-1.x

#318 Backport #316 to 1.x
  packages/jupyter-ai/jupyter_ai/handlers.py
Labels: bug

#320 Update magics.ipynb
  examples/magics.ipynb
Labels: @jupyter-ai/magics

#209 Add GPT4All local provider
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/src/components/settings/model-fields.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement

#334 Add GPT4All local provider (1.x)
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/src/components/settings/model-fields.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement

#330 howto add key
  README.md
Labels: documentation, enhancement

#338 Update README.md
  README.md
Labels: documentation

#337 Add new 0613 GPT-3.5 and GPT-4 models
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#340 Add new 0613 GPT-3.5 and GPT-4 models
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#322 Azure OpenAI and OpenAI proxy support
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement, backport-1.x

#342 [1.x] Azure OpenAI and OpenAI proxy support
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement

#347 Update README, docs
  README.md
  docs/source/_static/jupyter-ai-screenshot.png
  docs/source/contributors/index.md
  docs/source/index.md
Labels: documentation, enhancement

#364 fix newline typo in improve_code
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
Labels: bug, @jupyter-ai/chatui

#371 Remove front end unit tests from code and README.md
  packages/jupyter-ai/README.md
  packages/jupyter-ai/src/__tests__/jupyter_gai.spec.ts
Labels: documentation, testing

#368 Added alias for bedrock titan model
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: enhancement

#363 relax pinning on importlib_metadata, typing_extensions
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/pyproject.toml
Labels: maintenance
