Repository jupyterlab/jupyter-ai, pull requests merged in 2023-04, with the labels that each got.

#22 Initial docs
  docs/Makefile
  docs/make.bat
  docs/requirements.txt
  docs/source/_static/codify-cell-menu.png
  docs/source/_static/gai-explain-code.gif
  docs/source/_static/generate-code-dialog-description.png
  docs/source/_static/generate-output-dialog.png
  docs/source/_static/generate-output-from-selection.png
  docs/source/_static/jupyter-ai-toolbar.png
  docs/source/_static/jupyter_logo.png
  docs/source/conf.py
  docs/source/contributors/index.md
  docs/source/index.md
  docs/source/users/index.md
Labels: documentation, enhancement

#24 Update README.md
  README.md
Labels: documentation, enhancement

#23 Use new provider interface in magics
  .gitignore
  packages/jupyter-ai/jupyter_ai/__init__.py
  packages/jupyter-ai/jupyter_ai/magics.py
  packages/jupyter-ai/jupyter_ai/providers.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
  packages/jupyter-ai/jupyter_ai/tests/test_providers.py
  packages/jupyter-ai/pyproject.toml
Labels: enhancement

#26 Update config.example.py
  playground/config.example.py
Labels: bug

#30 Add magics example notebook
  examples/magics.ipynb
  packages/jupyter-ai/jupyter_ai/magics.py
Labels: documentation, enhancement

#29 Removes docs about dialog, replaces with magics
  docs/source/_static/codify-cell-menu.png
  docs/source/_static/gai-explain-code.gif
  docs/source/_static/generate-code-dialog-description.png
  docs/source/_static/generate-output-dialog.png
  docs/source/_static/generate-output-from-selection.png
  docs/source/_static/jupyter-ai-toolbar.png
  docs/source/index.md
  docs/source/users/index.md
Labels: documentation, enhancement

#31 Magic tweaks
  packages/jupyter-ai/jupyter_ai/magics.py
Labels: enhancement

#32 Various magic enhancements and fixes
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/providers.py
  packages/jupyter-ai/pyproject.toml
Labels: bug, enhancement

#33 Documents changes while server is running
  docs/source/contributors/index.md
Labels: documentation, enhancement

#40 Chat backend
  .gitignore
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/providers.py
  packages/jupyter-ai/src/chat_handler.ts
  packages/jupyter-ai/src/handler.ts
Labels: enhancement

#25 Implement chat UI
  package.json
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/providers.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/schema/plugin.json
  packages/jupyter-ai/src/chat_handler.ts
  packages/jupyter-ai/src/components/chat-code-view.tsx
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/jl-theme-provider.tsx
  packages/jupyter-ai/src/components/open-task-dialog.tsx
  packages/jupyter-ai/src/contexts/selection-context.tsx
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/src/icons.ts
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/selection-watcher.ts
  packages/jupyter-ai/src/theme-provider.ts
  packages/jupyter-ai/src/utils.ts
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
  yarn.lock
Labels: enhancement

#48 Move magics to `jupyter-ai-magics` package
  .jupyter-releaser.toml
  README.md
  docs/source/contributors/index.md
  lerna.json
  nx.json
  package.json
  packages/jupyter-ai-chatgpt/package.json
  packages/jupyter-ai-dalle/package.json
  packages/jupyter-ai-magics/.gitignore
  packages/jupyter-ai-magics/LICENSE
  packages/jupyter-ai-magics/README.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/__init__.py
  packages/jupyter-ai-magics/package.json
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai-magics/setup.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/package.json
  packages/jupyter-ai/jupyter_ai/__init__.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/tests/test_providers.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/project.json
  packages/jupyter-ai/pyproject.toml
  pyproject.toml
  scripts/install.sh
  yarn.lock
Labels: enhancement

#49 use --force-publish option for lerna version
  scripts/bump-version.sh
Labels: bug, enhancement

#51 Make provider call async
  packages/jupyter-ai/jupyter_ai/handlers.py
Labels: enhancement

#53 Adds prompt templates
  examples/magics.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: enhancement, @jupyter-ai/magics

#34 Adds Err array with exceptions captured
  examples/errors.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/exception.py
  packages/jupyter-ai/jupyter_ai/__init__.py
Labels: enhancement

#54 make selections more robust
  packages/jupyter-ai/src/commands.ts
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/contexts/selection-context.tsx
  packages/jupyter-ai/src/selection-watcher.ts
  packages/jupyter-ai/src/utils.ts
Labels: enhancement

#57 Adds code format option
  docs/source/users/index.md
  examples/code.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: enhancement, @jupyter-ai/magics

#56 Updates README, adds screen shots
  README.md
  docs/source/_static/sample-code.png
  docs/source/_static/sample-html-math.png
  docs/source/_static/sample-markdown.png
Labels: bug, documentation

#58 Basic collaborative chat
  .gitignore
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/chat_handler.ts
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
Labels: enhancement

#60 Strips prefix and suffix
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: bug, @jupyter-ai/magics

#65 implement better chat history UI
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/scroll-container.tsx
  packages/jupyter-ai/src/contexts/collaborators-context.tsx
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
  yarn.lock
Labels: enhancement

#63 Documents special error list, updates example file
  docs/source/users/index.md
  examples/errors.ipynb
Labels: bug, documentation

#70 General UI/UX improvements
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/icons.ts
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
  packages/jupyter-ai/style/base.css
  packages/jupyter-ai/style/icons/chat.svg
  packages/jupyter-ai/style/react-markdown.css
Labels: enhancement, @jupyter-ai/chatui

#71 Removes chatgpt, dalle modules
  .jupyter-releaser.toml
  packages/jupyter-ai-chatgpt/.eslintignore
  packages/jupyter-ai-chatgpt/.eslintrc.js
  packages/jupyter-ai-chatgpt/.gitignore
  packages/jupyter-ai-chatgpt/.prettierignore
  packages/jupyter-ai-chatgpt/.prettierrc
  packages/jupyter-ai-chatgpt/.stylelintrc
  packages/jupyter-ai-chatgpt/LICENSE
  packages/jupyter-ai-chatgpt/README.md
  packages/jupyter-ai-chatgpt/babel.config.js
  packages/jupyter-ai-chatgpt/install.json
  packages/jupyter-ai-chatgpt/jest.config.js
  packages/jupyter-ai-chatgpt/jupyter_ai_chatgpt/__init__.py
  packages/jupyter-ai-chatgpt/jupyter_ai_chatgpt/engine.py
  packages/jupyter-ai-chatgpt/jupyter_ai_chatgpt/tests/__init__.py
  packages/jupyter-ai-chatgpt/package.json
  packages/jupyter-ai-chatgpt/pyproject.toml
  packages/jupyter-ai-chatgpt/setup.py
  packages/jupyter-ai-chatgpt/src/__tests__/jupyter_ai_chatgpt.spec.ts
  packages/jupyter-ai-chatgpt/src/index.ts
  packages/jupyter-ai-chatgpt/style/base.css
  packages/jupyter-ai-chatgpt/style/index.css
  packages/jupyter-ai-chatgpt/style/index.js
  packages/jupyter-ai-chatgpt/tsconfig.json
  packages/jupyter-ai-chatgpt/ui-tests/README.md
  packages/jupyter-ai-chatgpt/ui-tests/jupyter_server_test_config.py
  packages/jupyter-ai-chatgpt/ui-tests/package.json
  packages/jupyter-ai-chatgpt/ui-tests/playwright.config.js
  packages/jupyter-ai-chatgpt/ui-tests/tests/jupyter_ai_chatgpt.spec.ts
  packages/jupyter-ai-dalle/.eslintignore
  packages/jupyter-ai-dalle/.eslintrc.js
  packages/jupyter-ai-dalle/.gitignore
  packages/jupyter-ai-dalle/.prettierignore
  packages/jupyter-ai-dalle/.prettierrc
  packages/jupyter-ai-dalle/.stylelintrc
  packages/jupyter-ai-dalle/LICENSE
  packages/jupyter-ai-dalle/README.md
  packages/jupyter-ai-dalle/babel.config.js
  packages/jupyter-ai-dalle/install.json
  packages/jupyter-ai-dalle/jest.config.js
  packages/jupyter-ai-dalle/jupyter_ai_dalle/__init__.py
  packages/jupyter-ai-dalle/jupyter_ai_dalle/engine.py
  packages/jupyter-ai-dalle/jupyter_ai_dalle/tasks.py
  packages/jupyter-ai-dalle/jupyter_ai_dalle/tests/__init__.py
  packages/jupyter-ai-dalle/package.json
  packages/jupyter-ai-dalle/pyproject.toml
  packages/jupyter-ai-dalle/setup.py
  packages/jupyter-ai-dalle/src/__tests__/jupyter_ai_dalle.spec.ts
  packages/jupyter-ai-dalle/src/index.ts
  packages/jupyter-ai-dalle/style/base.css
  packages/jupyter-ai-dalle/style/index.css
  packages/jupyter-ai-dalle/style/index.js
  packages/jupyter-ai-dalle/tsconfig.json
  packages/jupyter-ai-dalle/ui-tests/README.md
  packages/jupyter-ai-dalle/ui-tests/jupyter_server_test_config.py
  packages/jupyter-ai-dalle/ui-tests/package.json
  packages/jupyter-ai-dalle/ui-tests/playwright.config.js
  packages/jupyter-ai-dalle/ui-tests/tests/jupyter_ai_dalle.spec.ts
  playground/config.example.py
Labels: enhancement, maintenance, @jupyter-ai/chatgpt, @jupyter-ai/dalle

#74 Documents requirements to use Python 3.10, JupyterLab
  docs/source/contributors/index.md
  docs/source/users/index.md
  packages/jupyter-ai/pyproject.toml
Labels: bug, documentation

#77 Remove old UI
  packages/jupyter-ai/src/__tests__/commands.spec.ts
  packages/jupyter-ai/src/commands.ts
  packages/jupyter-ai/src/index.ts
Labels: maintenance

#79 Removed sleep that was slowing replies down
  packages/jupyter-ai/jupyter_ai/reply_processor.py
Labels: bug, @jupyter-ai/chatui

#78 Add a /clear command to clear the chat history
  packages/jupyter-ai/jupyter_ai/actors.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement, @jupyter-ai/chatui

#80 Moved actors to separate modules.
  packages/jupyter-ai/jupyter_ai/actors.py
  packages/jupyter-ai/jupyter_ai/actors/__init__.py
  packages/jupyter-ai/jupyter_ai/actors/base.py
  packages/jupyter-ai/jupyter_ai/actors/default.py
  packages/jupyter-ai/jupyter_ai/actors/filesystem.py
  packages/jupyter-ai/jupyter_ai/actors/index.py
  packages/jupyter-ai/jupyter_ai/actors/router.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/pyproject.toml
  yarn.lock
Labels: maintenance, @jupyter-ai/core

#88 Error handling and messaging when the chat service doesn't work
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/src/chat_handler.ts
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/widgets/chat-error.tsx
Labels: bug

#89 Added support to index py, ipynb, md, and R files
  packages/jupyter-ai/jupyter_ai/actors/index.py
  packages/jupyter-ai/jupyter_ai/document_loaders/__init__.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  packages/jupyter-ai/pyproject.toml
Labels: enhancement

#94 Ray based document parsing of more file types
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/actors/ask.py
  packages/jupyter-ai/jupyter_ai/actors/base.py
  packages/jupyter-ai/jupyter_ai/actors/default.py
  packages/jupyter-ai/jupyter_ai/actors/index.py
  packages/jupyter-ai/jupyter_ai/actors/learn.py
  packages/jupyter-ai/jupyter_ai/actors/memory.py
  packages/jupyter-ai/jupyter_ai/actors/router.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  packages/jupyter-ai/jupyter_ai/document_loaders/splitter.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/pyproject.toml
Labels: enhancement, @jupyter-ai/chatui

#90 Create /autonotebook command for AI generated notebooks
  examples/generate/Creating Random Arrays with Numpy.ipynb
  examples/generate/Python Sets Tutorial.ipynb
  examples/generate/Training Dense Neural Network with PyTorch.ipynb
  packages/jupyter-ai/jupyter_ai/actors/base.py
  packages/jupyter-ai/jupyter_ai/actors/generate.py
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: enhancement, @jupyter-ai/chatui

#99 Removes version from docs config
  docs/source/conf.py
Labels: documentation, enhancement

#109 Updates contributor docs with more info about prerequisites
  docs/source/contributors/index.md
Labels: documentation, enhancement

#116 Update chat interface privacy and cost notice
  docs/source/users/index.md
Labels: documentation, enhancement

#114 Implement better non-collaborative identity
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
Labels: enhancement

#100 Adds %ai list, %ai help magic commands
  docs/source/users/index.md
  examples/commands.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement, @jupyter-ai/magics

#120 Docs: Moves chat icon to left tab bar
  docs/source/_static/chat-icon-left-tab-bar.png
  docs/source/_static/chat-interface-blank.png
  docs/source/users/index.md
Labels: documentation, enhancement

#126 Strips language indicator from start of code output
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: bug, @jupyter-ai/magics
