Repository jupyterlab/jupyter-ai, pull requests merged in 2023-07, with the labels that each got.

#249 Fix settings update and vertical scroll
  packages/jupyter-ai/jupyter_ai/actors/base.py
  packages/jupyter-ai/src/components/chat-settings.tsx
Labels: bug

#251 Fixes "replace selection" behavior when nothing is selected
  packages/jupyter-ai/src/selection-watcher.ts
Labels: bug, @jupyter-ai/chatui

#244 Migrate to Dask
  .github/workflows/check-release.yml
  .github/workflows/lint.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  README.md
  docs/source/contributors/index.md
  docs/source/users/index.md
  examples/generate/Creating Random Arrays with Numpy.ipynb
  examples/generate/Introduction to Sets.ipynb
  examples/generate/Python Sets Tutorial.ipynb
  examples/generate/Training Dense Neural Network with PyTorch.ipynb
  examples/generate/Training a Dense Neural Network with PyTorch.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/utils.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/README.md
  packages/jupyter-ai/jupyter_ai/__init__.py
  packages/jupyter-ai/jupyter_ai/actors/__init__.py
  packages/jupyter-ai/jupyter_ai/actors/base.py
  packages/jupyter-ai/jupyter_ai/actors/chat_provider.py
  packages/jupyter-ai/jupyter_ai/actors/config.py
  packages/jupyter-ai/jupyter_ai/actors/embeddings_provider.py
  packages/jupyter-ai/jupyter_ai/actors/memory.py
  packages/jupyter-ai/jupyter_ai/actors/providers.py
  packages/jupyter-ai/jupyter_ai/actors/router.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/__init__.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/clear.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  packages/jupyter-ai/jupyter_ai/engine.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/reply_processor.py
  packages/jupyter-ai/jupyter_ai/task_manager.py
  packages/jupyter-ai/jupyter_ai/tasks.py
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/inserter.ts
  scripts/install.sh
Labels: enhancement

#254 Updates docs with reset, model lists
  docs/source/users/index.md
  examples/commands.ipynb
  examples/images.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: documentation, enhancement, @jupyter-ai/magics

#263 Added Bedrock provider
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: bug, enhancement

#265 Sets font color for intro text
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/style/chat-settings.css
Labels: bug, @jupyter-ai/chatui

#267 Allows specifying chunk size and overlap with /learn
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/models.py
Labels: enhancement

#286 fix /learn TypeError
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
Labels: bug

#277 Chat help message on load
  packages/jupyter-ai/jupyter_ai/chat_handlers/__init__.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/style/react-markdown.css
Labels: enhancement, @jupyter-ai/chatui

#296 Upgrade to JupyterLab 4
  .github/workflows/lint.yml
  .gitignore
  .jupyter-releaser.toml
  .yarnrc.yml
  README.md
  docs/source/users/index.md
  package.json
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.github/workflows/build.yml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.github/workflows/update-integration-tests.yml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/README.md
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/binder/environment.yml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/pyproject.toml
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/selection-watcher.ts
  packages/jupyter-ai/src/utils.ts
  pyproject.toml
  scripts/install.sh
  yarn.lock
Labels: enhancement

#300 Updates docs to refer to JupyterLab versions
  docs/source/contributors/index.md
  docs/source/index.md
Labels: documentation, enhancement
