Repository jupyterlab/jupyter-ai, pull requests merged in 2023-06, with the labels that each got.

#197 Support SageMaker Endpoints in chat
  .github/workflows/check-release.yml
  docs/source/_static/chat-sagemaker-endpoints.png
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/actors/chat_provider.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/settings/model-fields.tsx
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/style/base.css
  packages/jupyter-ai/style/chat-settings.css
Labels: enhancement

#212 Pinning python version to 3.10.x
  .github/workflows/check-release.yml
Labels: maintenance

#170 Adds %ai error magic command to explain the most recent error
  docs/source/users/index.md
  examples/commands.ipynb
  examples/errors.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
Labels: enhancement, @jupyter-ai/magics

#213 Removes comment from magic command
  examples/magics.ipynb
Labels: bug, @jupyter-ai/magics

#136 Register, update, and delete aliases
  docs/source/users/index.md
  examples/commands.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
Labels: enhancement, @jupyter-ai/magics

#219 Creates a new websocket connection in case of disconnect
  packages/jupyter-ai/src/chat_handler.ts
Labels: bug

#220 Fixes double call to cell help command
  examples/commands.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: bug, @jupyter-ai/magics

#221 Update system prompt
  packages/jupyter-ai/jupyter_ai/actors/default.py
Labels: bug

#222 Only attempt re-connect on abnormal closure
  packages/jupyter-ai/src/chat_handler.ts
Labels: bug

#223 Added python version to release action
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
Labels: maintenance

#230 add JS lint workflow
  .github/workflows/lint.yml
  packages/jupyter-ai/.eslintignore
  packages/jupyter-ai/.eslintrc.js
  packages/jupyter-ai/.stylelintrc
  packages/jupyter-ai/README.md
  packages/jupyter-ai/src/chat_handler.ts
  packages/jupyter-ai/src/components/chat-code-view.tsx
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/jl-theme-provider.tsx
  packages/jupyter-ai/src/components/scroll-container.tsx
  packages/jupyter-ai/src/components/select.tsx
  packages/jupyter-ai/src/components/settings/model-fields.tsx
  packages/jupyter-ai/src/contexts/collaborators-context.tsx
  packages/jupyter-ai/src/contexts/selection-context.tsx
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/inserter.ts
  packages/jupyter-ai/src/selection-watcher.ts
  packages/jupyter-ai/src/widgets/chat-error.tsx
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
  packages/jupyter-ai/src/widgets/closable-dialog.tsx
  packages/jupyter-ai/style/base.css
  packages/jupyter-ai/style/chat-settings.css
Labels: maintenance, @jupyter-ai/core

#237 Use pre-commit
  .pre-commit-config.yaml
  README.md
  docs/source/_static/css/custom.css
  docs/source/conf.py
  docs/source/contributors/index.md
  docs/source/index.md
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/aliases.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/exception.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/utils.py
  packages/jupyter-ai-magics/package.json
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai-magics/setup.py
  packages/jupyter-ai-module-cookiecutter/README.md
  packages/jupyter-ai-module-cookiecutter/hooks/post_gen_project.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.github/workflows/build.yml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/binder/postBuild
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/setup.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/ui-tests/jupyter_server_test_config.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/{{cookiecutter.python_name}}/__init__.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/{{cookiecutter.python_name}}/engine.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/{{cookiecutter.python_name}}/tasks.py
  packages/jupyter-ai/.gitignore
  packages/jupyter-ai/conftest.py
  packages/jupyter-ai/jupyter_ai/__init__.py
  packages/jupyter-ai/jupyter_ai/actors/__init__.py
  packages/jupyter-ai/jupyter_ai/actors/ask.py
  packages/jupyter-ai/jupyter_ai/actors/base.py
  packages/jupyter-ai/jupyter_ai/actors/chat_provider.py
  packages/jupyter-ai/jupyter_ai/actors/config.py
  packages/jupyter-ai/jupyter_ai/actors/default.py
  packages/jupyter-ai/jupyter_ai/actors/embeddings_provider.py
  packages/jupyter-ai/jupyter_ai/actors/generate.py
  packages/jupyter-ai/jupyter_ai/actors/learn.py
  packages/jupyter-ai/jupyter_ai/actors/memory.py
  packages/jupyter-ai/jupyter_ai/actors/providers.py
  packages/jupyter-ai/jupyter_ai/actors/router.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  packages/jupyter-ai/jupyter_ai/document_loaders/splitter.py
  packages/jupyter-ai/jupyter_ai/engine.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/reply_processor.py
  packages/jupyter-ai/jupyter_ai/task_manager.py
  packages/jupyter-ai/jupyter_ai/tasks.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/setup.py
  packages/jupyter-ai/style/icons/jupyternaut.svg
  packages/jupyter-ai/ui-tests/jupyter_server_test_config.py
  playground/config.example.py
  scripts/bump-version.sh
Labels: maintenance

#240 Truncate chat history to last 2 conversations
  docs/source/_static/chat-history-context-1.png
  docs/source/_static/chat-history-context-2.png
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/actors/ask.py
Labels: bug

#250 Adds __str__ method for TextWithMetadata
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: bug, @jupyter-ai/magics
