Repository jupyterlab/jupyter-ai, pull requests merged in 2023-10, with the labels that each got.

#403 Added missing code from backport.
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: maintenance

#415 Allow to define block and allow lists for providers
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_utils.py
  packages/jupyter-ai-magics/jupyter_ai_magics/utils.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_extension.py
  packages/jupyter-ai/pyproject.toml
Labels: enhancement

#417 Backport PRs 344, 407, 415
  .pre-commit-config.yaml
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_utils.py
  packages/jupyter-ai-magics/jupyter_ai_magics/utils.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_extension.py
  packages/jupyter-ai/pyproject.toml
Labels: maintenance

#420 Document how to add custom model providers
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/utils.py
  packages/jupyter-ai/jupyter_ai/handlers.py
Labels: documentation
