Repository jupyterlab/jupyter-ai, pull requests merged in 2024-01, with the labels that each got.

#558 Pin `langchain-core` dependency to prevent Settings UI crash
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/pyproject.toml
  pyproject.toml
Labels: bug

#559 Backport PR #558 on branch 1.x (Pin `langchain-core` dependency to prevent Settings UI crash)
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/pyproject.toml
  pyproject.toml
Labels: bug

#560 Fixes lookup for custom chains
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: bug

#561 Backport PR #560 on branch 1.x (Fixes lookup for custom chains)
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: bug

#565 Implement `stop_extension()`
  packages/jupyter-ai/jupyter_ai/extension.py
  yarn.lock
Labels: enhancement

#566 [1.x] Implement `stop_extension()`
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: enhancement

#551 Upgrades openai to version 1, removes openai history in magics
  README.md
  docs/source/users/index.md
  examples/commands.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/pyproject.toml
  yarn.lock
Labels: enhancement

#567 Backport PR #551 on branch 1.x (Upgrades openai to version 1, removes openai history in magics)"
  README.md
  docs/source/users/index.md
  examples/commands.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/pyproject.toml
Labels: enhancement

#572 LangChain v0.1.0
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_provider_metaclass.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/pyproject.toml
  pyproject.toml
Labels: enhancement

#573 Backport PR #572 on branch 1.x (LangChain v0.1.0)
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_provider_metaclass.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/pyproject.toml
  pyproject.toml
Labels: enhancement

#584 Update Cohere model IDs
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
Labels: bug

#586 Backport PR #584 on branch 1.x (Update Cohere model IDs)
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
Labels: bug

#582 Inline completion support
  package.json
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/completions/__init__.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/__init__.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/base.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/default.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/llm_mixin.py
  packages/jupyter-ai/jupyter_ai/completions/models.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/src/completions/handler.ts
  packages/jupyter-ai/src/completions/index.ts
  packages/jupyter-ai/src/completions/plugin.ts
  packages/jupyter-ai/src/completions/provider.ts
  packages/jupyter-ai/src/completions/types.ts
  packages/jupyter-ai/src/components/statusbar-item.tsx
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/selection-watcher.ts
  packages/jupyter-ai/src/status.ts
  packages/jupyter-ai/src/tokens.ts
  packages/jupyter-ai/style/icons/jupyternaut.svg
  yarn.lock
Labels: enhancement

#592 Fix streaming, add minimal tests
  packages/jupyter-ai/jupyter_ai/completions/handlers/base.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/default.py
  packages/jupyter-ai/jupyter_ai/tests/completions/__init__.py
  packages/jupyter-ai/jupyter_ai/tests/completions/test_handlers.py
Labels: bug

#594 Upgrades cohere dependency, model list
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: bug, @jupyter-ai/chatui

#596 Removes deprecated models, adds updated models for openai
  examples/commands.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/aliases.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/{{cookiecutter.python_name}}/engine.py
Labels: bug

#597 Backport PR #594 on branch 1.x (Upgrades cohere dependency, model list)
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: bug, @jupyter-ai/chatui

#575 Reflect theme changes without a refresh
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/jl-theme-provider.tsx
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/theme-provider.ts
  packages/jupyter-ai/src/widgets/chat-error.tsx
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
  yarn.lock
Labels: enhancement

#598 Backport PR #596 on branch 1.x (Removes deprecated models, adds updated models for openai)
  examples/commands.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/aliases.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/{{cookiecutter.python_name}}/engine.py
Labels: bug, @jupyter-ai/chatui

#599 Backport PR #575: Reflect theme changes without a refresh
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/jl-theme-provider.tsx
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/theme-provider.ts
  packages/jupyter-ai/src/widgets/chat-error.tsx
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
Labels: enhancement

#577 Add Kaggle to supported platforms
  README.md
Labels: documentation

#581 Expose templates for customisation in providers
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/default.py
Labels: enhancement

#600 Uses invoke() to call custom chains. Handles dict output format.
  examples/commands.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: bug, @jupyter-ai/magics

#601 Backport PR #600 on branch 1.x (Uses invoke() to call custom chains. Handles dict output format.)
  examples/commands.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: bug, @jupyter-ai/magics

#421 Setting default model providers
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
Labels: enhancement

#608 Backport PR #421 on branch 1.x (Setting default model providers)
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
Labels: enhancement

#602 Backport PR #581 on branch 1.x (Expose templates for customisation in providers)
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
Labels: enhancement

#609 Backport PR #605 on branch 1.x (Correction to default models configuration.)
  docs/source/users/index.md
Labels: documentation

#610 fix to conda install instructions in readme
  README.md
Labels: bug

#612 Backport PR #610: fix to conda install instructions in readme
  README.md
Labels: bug, documentation
