Repository jupyterlab/jupyter-ai, pull requests merged in 2024-09, with the labels that each got.

#951 Add ability to delete messages + start new chat session
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/clear.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/fix.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/history.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/chat_handler.ts
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/components/chat-messages/chat-message-delete.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/pending-messages.tsx
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/ui-tests/tests/jupyter-ai.spec.ts-snapshots/chat-welcome-message-linux.png
Labels: enhancement

#975 Fix sort messages
  packages/jupyter-ai/src/components/chat-messages.tsx
Labels: bug

#980 Fix `RunnableWithMessageHistory` import
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
Labels: bug

#981 Allow to disable automatic inline completions
  packages/jupyter-ai/src/completions/provider.ts
Labels: enhancement

#986 Allow unlimited LLM memory through traitlets configuration
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/history.py
  packages/jupyter-ai/jupyter_ai/tests/test_extension.py
Labels: enhancement

#992 Upgrade to `actions/upload-artifact@v4` in workflows
  .github/workflows/e2e-tests.yml
Labels: maintenance

#987 Run mypy on CI, fix or ignore typing issues
  .github/workflows/unit-tests.yml
  packages/jupyter-ai-magics/jupyter_ai_magics/models/completion.py
  packages/jupyter-ai-magics/jupyter_ai_magics/py.typed
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/fix.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/history.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/pyproject.toml
  pyproject.toml
Labels: bug

#989 Adds unix shell-style wildcard matching to `/learn`
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  packages/jupyter-ai/jupyter_ai/tests/static/file9.ipynb
  packages/jupyter-ai/jupyter_ai/tests/test_directory.py
Labels: enhancement

#996 Add OpenRouter support
  packages/jupyter-ai-magics/jupyter_ai_magics/aliases.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openrouter.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#993 Framework for adding context to LLM prompt
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/context_providers/__init__.py
  packages/jupyter-ai/jupyter_ai/context_providers/_learned.py
  packages/jupyter-ai/jupyter_ai/context_providers/base.py
  packages/jupyter-ai/jupyter_ai/context_providers/file.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/test_context_providers.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement

#1013 Add `metadata` field to agent messages
  packages/jupyter-ai-test/jupyter_ai_test/test_llms.py
  packages/jupyter-ai/jupyter_ai/callback_handlers/__init__.py
  packages/jupyter-ai/jupyter_ai/callback_handlers/metadata.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/chat_handler.ts
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/components/pending-messages.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement

#1015 Migrate to `ChatOllama` base class in Ollama provider
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/ollama.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement
