Repository jupyterlab/jupyter-ai, pull requests merged in 2024-11, with the labels that each got.

#1075 Fix magic commands when using non-chat providers w/ history
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: bug

#1077 Fix `/export` by including streamed agent messages
  packages/jupyter-ai/jupyter_ai/chat_handlers/export.py
Labels: bug

#1080 Backport PR #1075 on branch v3-dev (Fix magic commands when using non-chat providers w/ history)
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: bug

#1081 Backport PR #1077 on branch v3-dev (Fix `/export` by including streamed agent messages)
  packages/jupyter-ai/jupyter_ai/chat_handlers/export.py
Labels: bug

#1072 Reduced padding in cell around code icons in code toolbar
  packages/jupyter-ai/src/components/code-blocks/code-toolbar.tsx
  packages/jupyter-ai/src/components/mui-extras/tooltipped-icon-button.tsx
Labels: enhancement

#1084 Backport PR #1072 on branch v3-dev (Reduced padding in cell around code icons in code toolbar)
  packages/jupyter-ai/src/components/code-blocks/code-toolbar.tsx
  packages/jupyter-ai/src/components/mui-extras/tooltipped-icon-button.tsx
Labels: enhancement

#1087 Improve installation documentation and clarify provider dependencies
  README.md
  docs/source/users/index.md
Labels: documentation

#1091 Backport PR #1087 on branch v3-dev (Improve installation documentation and clarify provider dependencies)
  README.md
  docs/source/users/index.md
Labels: documentation

#1092 Remove retired models and add new `Haiku-3.5` model in Anthropic
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/anthropic.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/aws.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#1093 Backport PR #1092 on branch v3-dev (Remove retired models and add new `Haiku-3.5` model in Anthropic)
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/anthropic.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/aws.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#1094 Continue to allow `$` symbols to delimit inline math in human messages
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/src/components/rendermime-markdown.tsx
Labels: bug

#1095 Backport PR #1094 on branch v3-dev (Continue to allow `$` symbols to delimit inline math in human messages)
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/src/components/rendermime-markdown.tsx
Labels: bug

#1097 Update `faiss-cpu` version range
  packages/jupyter-ai/pyproject.toml
Labels: bug, dependency:faiss-cpu

#1101 Backport PR #1097 on branch v3-dev (Update `faiss-cpu` version range)
  packages/jupyter-ai/pyproject.toml
Labels: bug, dependency:faiss-cpu

#1104 Fix rendering of code blocks in JupyterLab 4.3.0+
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/style/rendermime-markdown.css
Labels: bug

#1105 Backport PR #1104 on branch v3-dev (Fix rendering of code blocks in JupyterLab 4.3.0+)
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/style/rendermime-markdown.css
Labels: bug

#1106 Catch error on non plaintext files in `@file` and reply gracefully in chat
  packages/jupyter-ai/jupyter_ai/context_providers/file.py
Labels: bug

#1110 Backport PR #1106 on branch v3-dev (Catch error on non plaintext files in `@file` and reply gracefully in chat)
  packages/jupyter-ai/jupyter_ai/context_providers/file.py
Labels: bug

#1109 Bump LangChain minimum versions
  packages/jupyter-ai-magics/pyproject.toml
Labels: bug

#1112 Backport PR #1109 on branch v3-dev (Bump LangChain minimum versions)
  packages/jupyter-ai-magics/pyproject.toml
Labels: bug

#1119 Downgrade spurious 'error' logs
  packages/jupyter-ai-magics/jupyter_ai_magics/utils.py
Labels: bug

#1124 Backport PR #1119 on branch v3-dev (Downgrade spurious 'error' logs)
  packages/jupyter-ai-magics/jupyter_ai_magics/utils.py
Labels: bug
