Repository jupyterlab/jupyter-ai, pull requests merged in 2024-06, with the labels that each got.

#810 Autocomplete UI for slash commands
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/export.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement

#811 Refactor split function with tests
  conftest.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  packages/jupyter-ai/jupyter_ai/tests/static/.hidden_file.pdf
  packages/jupyter-ai/jupyter_ai/tests/static/.hidden_file.txt
  packages/jupyter-ai/jupyter_ai/tests/static/file0.html
  packages/jupyter-ai/jupyter_ai/tests/static/file1.txt
  packages/jupyter-ai/jupyter_ai/tests/static/file2.py
  packages/jupyter-ai/jupyter_ai/tests/static/file3.csv
  packages/jupyter-ai/jupyter_ai/tests/static/file3.xyz
  packages/jupyter-ai/jupyter_ai/tests/static/file4.pdf
  packages/jupyter-ai/jupyter_ai/tests/test_directory.py
Labels: enhancement

#777 Document how to create completions using full notebook content
  docs/source/developers/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: documentation

#824 Fix import deprecations
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: maintenance

#823 Add support for MistralAI
  README.md
  docs/source/index.md
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/mistralai.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#828 Add `/fix` slash command
  docs/source/_static/fix-error-cell-selected.png
  docs/source/_static/fix-no-error-cell-selected.png
  docs/source/_static/fix-response.png
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/chat_handlers/__init__.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/fix.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/components/chat-input/send-button.tsx
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/code-blocks/code-toolbar.tsx
  packages/jupyter-ai/src/components/mui-extras/tooltipped-icon-button.tsx
  packages/jupyter-ai/src/contexts/active-cell-context.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement

#825 Prevent overriding `server_settings` on base provider class
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_provider_metaclass.py
Labels: maintenance

#834 Add new Cohere models
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#827 Support Notebook 7
  README.md
  docs/source/users/index.md
  package.json
  packages/jupyter-ai/package.json
  packages/jupyter-ai/src/contexts/active-cell-context.tsx
  packages/jupyter-ai/src/selection-watcher.ts
  packages/jupyter-ai/src/status.ts
  yarn.lock
Labels: enhancement

#821 Support pending/loading message while waiting for response
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/fix.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/pending-messages.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement

#832 Group messages with their replies
  packages/jupyter-ai/src/components/chat-messages.tsx
Labels: enhancement

#844 Fix compatibility with Python 3.8
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: bug

#843 Updates end of maintenance messaging to be in the past tense
  README.md
  docs/source/users/index.md
Labels: documentation

#847 Add claude sonnet 3.5 models
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/anthropic.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#846 Update `clear` slash command to use `HelpChatHandler` to reinstate the help menu
  packages/jupyter-ai/jupyter_ai/chat_handlers/clear.py
Labels: enhancement, @jupyter-ai/chatui

#848 Fix Cohere models by using new `langchain-cohere` partner package
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/cohere.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: bug

#850 Fix send via keyboard after sending slash command with arguments
  packages/jupyter-ai/src/components/chat-input.tsx
Labels: bug

#854 Fixed `/export` for timestamp, agent name
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/chat_handlers/export.py
Labels: bug

#855 Fixes error when allowed or blocked model list is passed in config
  packages/jupyter-ai/jupyter_ai/handlers.py
Labels: bug

#859 Implement LLM response streaming
  .gitignore
  packages/jupyter-ai-magics/.gitignore
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-test/LICENSE
  packages/jupyter-ai-test/README.md
  packages/jupyter-ai-test/jupyter_ai_test/__init__.py
  packages/jupyter-ai-test/jupyter_ai_test/test_llms.py
  packages/jupyter-ai-test/jupyter_ai_test/test_providers.py
  packages/jupyter-ai-test/jupyter_ai_test/test_slash_commands.py
  packages/jupyter-ai-test/jupyter_ai_test/tests/__init__.py
  packages/jupyter-ai-test/package.json
  packages/jupyter-ai-test/project.json
  packages/jupyter-ai-test/pyproject.toml
  packages/jupyter-ai-test/setup.py
  packages/jupyter-ai/.gitignore
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/history.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/src/chat_handler.ts
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/rendermime-markdown.tsx
  packages/jupyter-ai/src/handler.ts
  yarn.lock
Labels: enhancement
