Repository jupyterlab/jupyter-ai, pull requests merged in 2024-08, with the labels that each got.

#918 Settings section improvement
  packages/jupyter-ai/src/components/chat-settings.tsx
Labels: enhancement

#946 Fix sending empty input with Enter
  packages/jupyter-ai/src/components/chat-input.tsx
Labels: bug

#942 Add optional configurable message footer
  docs/source/developers/index.md
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/tokens.ts
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
Labels: enhancement

#940 Add support for Azure Open AI Embeddings to Jupyter AI
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#949 Bind reject method to promise, improve typing
  packages/jupyter-ai/src/completions/handler.ts
Labels: bug

#938 Make help message template configurable
  docs/source/_static/chat-icon-left-tab-bar-custom.png
  docs/source/_static/chat-icon-left-tab-bar.png
  docs/source/users/index.md
  packages/jupyter-ai-test/jupyter_ai_test/test_providers.py
  packages/jupyter-ai-test/pyproject.toml
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/clear.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
Labels: enhancement

#961 Update documentation to cover installation of all dependencies
  docs/source/users/index.md
Labels: documentation

#962 Allow configuring a default model for cell magics (and line error magic)
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/exception.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_magics.py
Labels: enhancement

#943 Make chat memory size traitlet configurable + /clear to reset memory
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/clear.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/history.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
  packages/jupyter-ai/src/chat_handler.ts
Labels: enhancement

#971 Add 'Generative AI' submenu
  packages/jupyter-ai/src/components/chat-input/send-button.tsx
  packages/jupyter-ai/src/contexts/active-cell-context.tsx
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/plugins/menu-plugin.ts
  packages/jupyter-ai/src/selection-watcher.ts
  packages/jupyter-ai/src/tokens.ts
Labels: enhancement
