Repository jupyterlab/jupyter-ai, pull requests merged in 2024-03, with the labels that each got.

#654 Together.ai provider added
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#674 Backport PR #654 on branch 1.x (Together.ai provider added)
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#665 %ai version added
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
Labels: enhancement

#676 Backport PR #665 on branch 1.x (%ai version added)
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
Labels: enhancement

#656 fix bug: check before using the variables
  packages/jupyter-ai/jupyter_ai/completions/handlers/llm_mixin.py
Labels: bug

#666 Add support for Gemini
  README.md
  docs/source/index.md
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/gemini.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#678 Backport PR #666 on branch 1.x (Add support for Gemini)
  README.md
  docs/source/index.md
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/gemini.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#675 Use regex in TeX replace function to catch repeating symbol occurrences
  packages/jupyter-ai/src/components/rendermime-markdown.tsx
Labels: bug

#681 Backport PR #675 on branch 1.x (Use regex in TeX replace function to catch repeating symbol occurrences)
  packages/jupyter-ai/src/components/rendermime-markdown.tsx
Labels: bug

#682 Fix selecting models with a colon in their ID
  packages/jupyter-ai/src/components/chat-settings.tsx
Labels: bug

#683 Backport PR #682 on branch 1.x (Fix selecting models with a colon in their ID)
  packages/jupyter-ai/src/components/chat-settings.tsx
Labels: bug

#672 Add Anthropic Claude 3 models to providers
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#660 Resolves chat panel initialization error
  packages/jupyter-ai/jupyter_ai/handlers.py
Labels: bug

#658 /export added
  packages/jupyter-ai/jupyter_ai/chat_handlers/__init__.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/export.py
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: enhancement

#693 Backport PR #658 on branch 1.x (/export added)
  packages/jupyter-ai/jupyter_ai/chat_handlers/__init__.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/export.py
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: enhancement

#696 Add Claude-3-Haiku
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#697 [1.x] Add Claude-3-Haiku (#696)
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#691 Use `AZURE_OPENAI_API_KEY` for Azure OpenAI provider
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#699 Backport PR #691 on branch 1.x (Use `AZURE_OPENAI_API_KEY` for Azure OpenAI provider)
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#653 Use new `langchain-openai` partner package
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/pyproject.toml
Labels: bug

#703 Backport PR #653 on branch 1.x (Use new `langchain-openai` partner package)
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/pyproject.toml
Labels: bug

#700 Update Anthropic providers to use `langchain_anthropic` partner package
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/anthropic.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: bug, enhancement

#705 Backport PR #700 on branch 1.x (Update Anthropic providers to use langchain_anthropic partner package)
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/anthropic.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: bug, enhancement

#704 Fix rendering of model IDs with a colon in their name
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/settings/use-server-info.ts
  packages/jupyter-ai/src/utils.ts
Labels: bug

#707 Backport PR #704 on branch 1.x (Fix rendering of model IDs with a colon in their name)
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/settings/use-server-info.ts
  packages/jupyter-ai/src/utils.ts
Labels: bug
