Repository jupyterlab/jupyter-ai, pull requests merged in 2024-04, with the labels that each got.

#713 Improve support for custom providers
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/models/persona.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/static/jupyternaut.svg
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/src/icons.ts
Labels: enhancement

#715 Backport PR #713 on branch 1.x (Improve support for custom providers)
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/models/persona.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/static/jupyternaut.svg
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/src/icons.ts
Labels: enhancement

#712 Handle Single Files and also enable html, pdf file formats for /learn
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  packages/jupyter-ai/pyproject.toml
Labels: bug, enhancement

#723 Backport PR #712 on branch 1.x (Handle Single Files and also enable html, pdf file formats for /learn)
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  packages/jupyter-ai/pyproject.toml
Labels: bug, enhancement

#731 Require `jupyter_ai_magics` 2.13.0 to fix `Persona` import
  packages/jupyter-ai/pyproject.toml
Labels: bug, regression

#733 Handle single files, pdfs, errors from missing loader dependencies in `/learn`
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  packages/jupyter-ai/pyproject.toml
Labels: enhancement

#735 Catch embedding model validation errors on extension init
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
Labels: bug

#740 Backport PR #735 on branch 1.x (Catch embedding model validation errors on extension init)
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
Labels: bug

#722 Update Azure OpenAI fields
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
Labels: bug

#741 Backport PR #722 on branch 1.x (Update Azure OpenAI fields)
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
Labels: bug

#726 Remove trailing Markdown code tags in completion suggestions
  packages/jupyter-ai/jupyter_ai/completions/handlers/default.py
  packages/jupyter-ai/jupyter_ai/tests/completions/test_handlers.py
Labels: bug

#717 Move methods generating completion replies to the provider
  docs/source/developers/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/completion_utils.py
  packages/jupyter-ai-magics/jupyter_ai_magics/models/completion.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/base.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/default.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/llm_mixin.py
  packages/jupyter-ai/jupyter_ai/completions/models.py
  packages/jupyter-ai/jupyter_ai/tests/completions/test_handlers.py
Labels: enhancement

#743 Backport PR #729 on branch 1.x (Fixes help slash command.)
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
Labels: bug, regression

#744 Backport PR #733 on branch 1.x (Handle single files, pdfs, errors from missing loader dependencies in /learn)
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  packages/jupyter-ai/pyproject.toml
Labels: enhancement

#747 Fix /learn in 2.14.0
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
Labels: bug

#754 Backport PR #747 on branch 1.x (Fix /learn in 2.14.0)
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
Labels: bug

#752 Remove `pypdf` from required dependencies
  packages/jupyter-ai/pyproject.toml
Labels: bug

#755 Backport PR #752 on branch 1.x (Remove `pypdf` from required dependencies)
  packages/jupyter-ai/pyproject.toml
Labels: bug

#753 Load persisted vector store by default
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
Labels: bug

#756 Backport PR #753 on branch 1.x (Load persisted vector store by default)
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
Labels: bug

#758 Switch to langchain_community
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
Labels: bug

#760 Add JL3 end-of-maintenance notice to README and RTD
  README.md
  docs/source/users/index.md
Labels: documentation

#762 Backport PR #760 on branch 1.x (Add JL3 end-of-maintenance notice to README and RTD)
  README.md
  docs/source/users/index.md
Labels: documentation

#764 Updated LLM providers to Add New Bedrock Models IDs
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement
