Repository jupyterlab/jupyter-ai, pull requests merged in 2024-12, with the labels that each got.

#1127 Removes outdated OpenAI models and adds new ones
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
Labels: enhancement

#1130 Backport PR #1127 on branch v3-dev (Removes outdated OpenAI models and adds new ones)
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
Labels: enhancement

#1132 Backport PR #1131 on branch v3-dev ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: maintenance

#1125 Update model fields immediately on save
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
Labels: bug

#1133 Backport PR #1125 on branch v3-dev (Update model fields immediately on save)
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
Labels: bug

#1139 Fix install step in CI
  scripts/install.sh
Labels: bug

#1140 Backport PR #1139 on branch v3-dev (Fix install step in CI)
  scripts/install.sh
Labels: bug

#1129 Fix JSON serialization error in Ollama models
  packages/jupyter-ai/jupyter_ai/callback_handlers/metadata.py
  packages/jupyter-ai/jupyter_ai/models.py
Labels: bug

#1141 Backport PR #1129 on branch v3-dev (Fix JSON serialization error in Ollama models)
  packages/jupyter-ai/jupyter_ai/callback_handlers/metadata.py
  packages/jupyter-ai/jupyter_ai/models.py
Labels: bug

#1142 Backport PR #1137 on branch v3-dev (Update completion model fields immediately on save)
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
Labels: bug

#1134 Improve user messaging and documentation for Cross-Region Inference on Amazon Bedrock
  docs/source/_static/bedrock-chat-basemodel-arn.png
  docs/source/_static/bedrock-chat-basemodel-modelid.png
  docs/source/_static/bedrock-chat-custom-model-arn.png
  docs/source/_static/bedrock-cross-region-inference.png
  docs/source/_static/bedrock-model-select.png
  docs/source/users/bedrock.md
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/aws.py
Labels: documentation

#1143 Backport PR #1134 on branch v3-dev (Improve user messaging and documentation for Cross-Region Inference on Amazon Bedrock)
  docs/source/_static/bedrock-chat-basemodel-arn.png
  docs/source/_static/bedrock-chat-basemodel-modelid.png
  docs/source/_static/bedrock-chat-custom-model-arn.png
  docs/source/_static/bedrock-cross-region-inference.png
  docs/source/_static/bedrock-model-select.png
  docs/source/users/bedrock.md
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/aws.py
Labels: documentation

#1136 Add base API URL field for Ollama and OpenAI embedding models
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/ollama.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/src/components/chat-settings.tsx
Labels: enhancement

#1149 Backport PR #1136 on branch v3-dev (Add base API URL field for Ollama and OpenAI embedding models)
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/ollama.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/src/components/chat-settings.tsx
Labels: enhancement

#1148 [v3-dev] Remove `/export`, `/clear`, and `/fix`
  packages/jupyter-ai/jupyter_ai/chat_handlers/__init__.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/clear.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/export.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/fix.py
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: maintenance

#1154 Fix CI in `v3-dev` branch
  .github/workflows/check-release.yml
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/ui-tests/tests/jupyter-ai.spec.ts-snapshots/sidebar-linux.png
Labels: bug

#1151 [v3-dev] Dedicate one LangChain history object per chat
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/history.py
Labels: enhancement

#1161 Backport PR #1160 on branch v3-dev (Trigger update snapshots based on commenter's role)
  .github/workflows/update-snapshots.yml
  packages/jupyter-ai/ui-tests/tests/jupyter-ai.spec.ts-snapshots/chat-welcome-message-linux.png
Labels: maintenance

#1155 Fix code output format in IPython
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: bug

#1158 Update `/generate` to not split classes & functions across cells
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
Labels: bug

#1164 Backport PR #1158 on branch v3-dev (Update `/generate` to not split classes & functions across cells)
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
Labels: bug

#1156 Remove v2 frontend components
  packages/jupyter-ai/package.json
  packages/jupyter-ai/src/chat_handler.ts
  packages/jupyter-ai/src/completions/plugin.ts
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/components/chat-input/send-button.tsx
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/components/chat-messages/chat-message-delete.tsx
  packages/jupyter-ai/src/components/chat-messages/chat-message-menu.tsx
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/code-blocks/code-toolbar.tsx
  packages/jupyter-ai/src/components/expandable-text-field.tsx
  packages/jupyter-ai/src/components/mui-extras/tooltipped-button.tsx
  packages/jupyter-ai/src/components/pending-messages.tsx
  packages/jupyter-ai/src/components/rendermime-markdown.tsx
  packages/jupyter-ai/src/components/scroll-container.tsx
  packages/jupyter-ai/src/components/settings/rendermime-markdown.tsx
  packages/jupyter-ai/src/contexts/active-cell-context.tsx
  packages/jupyter-ai/src/contexts/collaborators-context.tsx
  packages/jupyter-ai/src/contexts/index.ts
  packages/jupyter-ai/src/contexts/selection-context.tsx
  packages/jupyter-ai/src/contexts/user-context.tsx
  packages/jupyter-ai/src/hooks/use-copy.ts
  packages/jupyter-ai/src/hooks/use-replace.ts
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/plugins/menu-plugin.ts
  packages/jupyter-ai/src/selection-watcher.ts
  packages/jupyter-ai/src/tokens.ts
  packages/jupyter-ai/src/utils.ts
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
  packages/jupyter-ai/ui-tests/tests/jupyter-ai.spec.ts
  yarn.lock
Labels: maintenance, @jupyter-ai/chatui

#1166 Upgrade to `jupyterlab-chat>=0.7.0`
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/history.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/pyproject.toml
  yarn.lock
Labels: enhancement

#1168 Remove v2 backend components
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/slash_command.py
  packages/jupyter-ai-test/jupyter_ai_test/test_slash_commands.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/utils/streaming.py
  packages/jupyter-ai/jupyter_ai/context_providers/_learned.py
  packages/jupyter-ai/jupyter_ai/context_providers/base.py
  packages/jupyter-ai/jupyter_ai/context_providers/file.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/history.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/test_context_providers.py
  packages/jupyter-ai/jupyter_ai/tests/test_extension.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/src/tokens.ts
  yarn.lock
Labels: enhancement

#1183 Reply gracefully when chat model is not selected
  .gitignore
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
Labels: bug
