Repository jupyterlab/jupyter-ai, pull requests merged in 2024-02, with the labels that each got.

#579 Add nvidia provider
  README.md
  docs/source/index.md
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#606 Restyles model names in Markdown to avoid wrapping model names
  examples/commands.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: enhancement, @jupyter-ai/magics

#615 Backport PR #606 on branch 1.x (Restyles model names in Markdown to avoid wrapping model names)
  examples/commands.ipynb
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
Labels: enhancement, @jupyter-ai/magics

#611 Mentions conda install instructions in docs
  README.md
  docs/source/users/index.md
Labels: documentation

#622 Allow usage without NVIDIA partner package
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/nvidia.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/utils.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: bug

#621 Bump `@jupyterlab/completer` resolution to `^4.1.0`
  package.json
  yarn.lock
Labels: enhancement

#626 Fix conda-forge typo in readme
  README.md
Labels: documentation

#627 Backport PR #626 on branch 1.x (Fix conda-forge typo in readme)
  README.md
Labels: documentation

#628 Add OpenAI text-embedding-3-small, -large models
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
Labels: enhancement, @jupyter-ai/chatui

#629 Backport PR #628 on branch 1.x (Add OpenAI text-embedding-3-small, -large models)
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
Labels: enhancement, @jupyter-ai/chatui

#564 Use @jupyterlab/rendermime for in-chat markdown rendering
  packages/jupyter-ai/package.json
  packages/jupyter-ai/src/components/chat-code-view.tsx
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/copy-button.tsx
  packages/jupyter-ai/src/components/rendermime-markdown.tsx
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
  packages/jupyter-ai/style/base.css
  packages/jupyter-ai/style/chat-settings.css
  packages/jupyter-ai/style/react-markdown.css
  packages/jupyter-ai/style/rendermime-markdown.css
  packages/jupyter-ai/ui-tests/tests/jupyter-ai.spec.ts-snapshots/chat-welcome-message-linux.png
  yarn.lock
Labels: enhancement

#631 [1.x] Use @jupyterlab/rendermime for in-chat markdown rendering
  packages/jupyter-ai/package.json
  packages/jupyter-ai/src/components/chat-code-view.tsx
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/copy-button.tsx
  packages/jupyter-ai/src/components/rendermime-markdown.tsx
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
  packages/jupyter-ai/style/base.css
  packages/jupyter-ai/style/chat-settings.css
  packages/jupyter-ai/style/react-markdown.css
  packages/jupyter-ai/style/rendermime-markdown.css
  yarn.lock
Labels: enhancement

#632 Unifies parameters to instantiate llm while incorporating model params
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/default.py
Labels: bug

#625 Add new OpenAI models
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#635 Backport PR #625 on branch 1.x (Add new OpenAI models)
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#637 Fix cookiecutter template
  .gitignore
  docs/source/developers/index.md
  packages/jupyter-ai-module-cookiecutter/.gitignore
  packages/jupyter-ai-module-cookiecutter/LICENSE
  packages/jupyter-ai-module-cookiecutter/README.md
  packages/jupyter-ai-module-cookiecutter/cookiecutter.json
  packages/jupyter-ai-module-cookiecutter/hooks/post_gen_project.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.eslintignore
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.eslintrc.js
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.github/workflows/binder-on-pr.yml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.github/workflows/build.yml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.github/workflows/check-release.yml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.github/workflows/update-integration-tests.yml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.gitignore
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.prettierignore
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.prettierrc
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.stylelintrc
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/CHANGELOG.md
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/README.md
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/RELEASE.md
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/babel.config.js
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/binder/environment.yml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/binder/postBuild
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/install.json
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/jest.config.js
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/package.json
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/pyproject.toml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/schema/plugin.json
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/src/__tests__/{{cookiecutter.python_name}}.spec.ts
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/src/index.ts
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/style/base.css
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/style/index.css
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/style/index.js
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/tsconfig.json
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/ui-tests/README.md
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/ui-tests/jupyter_server_test_config.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/ui-tests/package.json
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/ui-tests/playwright.config.js
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/ui-tests/tests/{{cookiecutter.python_name}}.spec.ts
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/{{cookiecutter.python_name}}/__init__.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/{{cookiecutter.python_name}}/engine.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/{{cookiecutter.python_name}}/tasks.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/LICENSE
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/README.md
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/pyproject.toml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/setup.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/__init__.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/llm.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/provider.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/slash_command.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/tests/__init__.py
  packages/jupyter-ai/jupyter_ai/__init__.py
Labels: documentation, enhancement

#640 Backport PR #637 on branch 1.x (Fix cookiecutter template)
  .gitignore
  docs/source/developers/index.md
  packages/jupyter-ai-module-cookiecutter/.gitignore
  packages/jupyter-ai-module-cookiecutter/LICENSE
  packages/jupyter-ai-module-cookiecutter/README.md
  packages/jupyter-ai-module-cookiecutter/cookiecutter.json
  packages/jupyter-ai-module-cookiecutter/hooks/post_gen_project.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.eslintignore
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.eslintrc.js
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.github/workflows/binder-on-pr.yml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.github/workflows/build.yml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.github/workflows/check-release.yml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.github/workflows/update-integration-tests.yml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.gitignore
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.prettierignore
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.prettierrc
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/.stylelintrc
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/CHANGELOG.md
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/README.md
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/RELEASE.md
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/babel.config.js
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/binder/environment.yml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/binder/postBuild
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/install.json
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/jest.config.js
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/package.json
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/pyproject.toml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/schema/plugin.json
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/src/__tests__/{{cookiecutter.python_name}}.spec.ts
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/src/index.ts
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/style/base.css
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/style/index.css
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/style/index.js
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/tsconfig.json
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/ui-tests/README.md
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/ui-tests/jupyter_server_test_config.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/ui-tests/package.json
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/ui-tests/playwright.config.js
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/ui-tests/tests/{{cookiecutter.python_name}}.spec.ts
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/{{cookiecutter.python_name}}/__init__.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/{{cookiecutter.python_name}}/engine.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.labextension_name}}/{{cookiecutter.python_name}}/tasks.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/LICENSE
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/README.md
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/pyproject.toml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/setup.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/__init__.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/llm.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/provider.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/slash_command.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/tests/__init__.py
  packages/jupyter-ai/jupyter_ai/__init__.py
Labels: documentation, enhancement

#642 Update docs to mention `langchain_community.llms`
  docs/source/developers/index.md
Labels: documentation

#643 Backport PR #642 on branch 1.x (Update docs to mention `langchain_community.llms`)
  docs/source/developers/index.md
Labels: documentation

#645 Add `nodejs=20` to the contributing docs
  docs/source/contributors/index.md
Labels: documentation
