Repository jupyterlab/jupyter-ai, pull requests merged in 2024-07, with the labels that each got.

#872 Fix plugin ID format
  packages/jupyter-ai/src/completions/plugin.ts
  packages/jupyter-ai/src/index.ts
Labels: bug

#873 Remove unused toolbars/menus from schema
  packages/jupyter-ai/schema/plugin.json
Labels: bug

#875 Do not redefine `refreshCompleterState` on each render
  packages/jupyter-ai/src/components/chat-settings.tsx
Labels: bug

#877 Limit chat input height to 20 lines
  packages/jupyter-ai/src/components/chat-input.tsx
Labels: bug

#870 Address error on `/learn` after change of embedding model
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
Labels: bug

#879 Fix prefix removal when streaming inline completions
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/tests/completions/test_handlers.py
Labels: bug

#876 Add keyboard shortcut command to focus chat input
  packages/jupyter-ai/schema/plugin.json
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
Labels: enhancement

#881 Make preferred-dir the default read/write directory for slash commands
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/export.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: bug

#878 Ensure all slash commands support `-h/--help`
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
Labels: enhancement

#887 Ensuring restricted access to the `/learn` index directory
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
Labels: bug

#646 Add Ollama
  README.md
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#893 Update to `actions/checkout@v4`
  .github/workflows/check-release.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/lint.yml
  .github/workflows/unit-tests.yml
Labels: maintenance

#892 Upload `jupyter-releaser` built distributions
  .github/workflows/check-release.yml
Labels: maintenance

#888 Fix removal of pending messages on error
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
Labels: bug

#894 Fix streaming in `HuggingFaceHub` provider
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: bug

#895 Rework selection replacement
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/components/chat-messages/chat-message-menu.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/code-blocks/code-toolbar.tsx
  packages/jupyter-ai/src/components/code-blocks/copy-button.tsx
  packages/jupyter-ai/src/hooks/use-copy.ts
  packages/jupyter-ai/src/hooks/use-replace.ts
Labels: enhancement

#897 Upgrade to `langchain~=0.2.0` and `langchain_community~=0.2.0`
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#898 Update docs to reflect Python 3.12 support
  README.md
  docs/source/contributors/index.md
  docs/source/users/index.md
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/README.md
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/pyproject.toml
  packages/jupyter-ai-test/README.md
  packages/jupyter-ai-test/pyproject.toml
  packages/jupyter-ai/README.md
  packages/jupyter-ai/pyproject.toml
Labels: documentation

#899 Fix python<3.10 compatibility
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
Labels: bug

#900 Trim leading whitespace when processing
  packages/jupyter-ai-magics/jupyter_ai_magics/completion_utils.py
  packages/jupyter-ai/jupyter_ai/tests/completions/test_handlers.py
Labels: bug

#901 Make magic aliases user-customizable
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_magics.py
Labels: enhancement

#904 Allow overriding the Ollama base URL
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#906 Add notebooks to the documentation
  .readthedocs.yaml
  docs/requirements.txt
  docs/source/conf.py
  docs/source/contributors/index.md
  docs/source/examples/code.nblink
  docs/source/examples/commands.nblink
  docs/source/examples/errors.nblink
  docs/source/examples/generate/Creating Random Arrays with Numpy.nblink
  docs/source/examples/generate/Introduction to Sets.nblink
  docs/source/examples/generate/index.md
  docs/source/examples/images.nblink
  docs/source/examples/index.md
  docs/source/examples/magics.nblink
  docs/source/examples/notebooks.nk
  docs/source/examples/sagemaker.nblink
  docs/source/index.md
Labels: documentation

#908 Added new Bedrock Llama 3.1 models and gpt-4o-mini
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#909 Migrate to `langchain-aws` for AWS providers
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/aws.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#916 Respect selected persona in chat input placeholder
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/components/chat.tsx
Labels: enhancement

#923 Add latest Bedrock models (Titan, Llama 3.1 405b, Mistral Large 2, Jamba Instruct)
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/aws.py
Labels: enhancement

#922 Add support for custom/provisioned models in Bedrock
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/aws.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#925 Update copyright template
  docs/source/conf.py
Labels: documentation
