Repository jupyterlab/jupyter-ai, pull requests merged in 2024-10, with the labels that each got.

#1012 Make path argument required on /learn
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
Labels: enhancement

#1019 Export tokens from `lib/index.js`
  packages/jupyter-ai/src/index.ts
Labels: bug

#997 Add back history and reset subcommand in magics
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_magics.py
Labels: enhancement

#1020 Export context hooks from NPM package entry point
  packages/jupyter-ai/src/contexts/index.ts
  packages/jupyter-ai/src/index.ts
Labels: enhancement

#1018 Add support for optional telemetry plugin
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/src/components/chat-messages.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/code-blocks/code-toolbar.tsx
  packages/jupyter-ai/src/components/code-blocks/copy-button.tsx
  packages/jupyter-ai/src/components/rendermime-markdown.tsx
  packages/jupyter-ai/src/contexts/index.ts
  packages/jupyter-ai/src/contexts/telemetry-context.tsx
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/tokens.ts
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
Labels: enhancement

#1029 Test Python 3.9 and 3.12 on CI, test minimum dependencies
  .github/workflows/unit-tests.yml
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_magics.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  pyproject.toml
  scripts/install.sh
Labels: maintenance

#1035 Support `jupyter-collaboration` v3
  packages/jupyter-ai/jupyter_ai/handlers.py
Labels: maintenance

#1022 Allow users to stop message streaming
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/components/chat-input/send-button.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/contexts/user-context.tsx
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
Labels: enhancement

#1024 Learn from JSON files
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
Labels: enhancement

#1038 Unify message clearing & broadcast logic
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/clear.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/src/components/chat-messages/chat-message-delete.tsx
  packages/jupyter-ai/src/handler.ts
Labels: enhancement

#1042 Remove clear_message_ids from RootChatHandler
  packages/jupyter-ai/jupyter_ai/handlers.py
Labels: enhancement

#1039 Migrate streaming logic to `BaseChatHandler`
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/fix.py
Labels: enhancement

#1045 Update requirements contributors doc
  docs/source/contributors/index.md
Labels: documentation, enhancement

#1047 Support Quarto Markdown in `/learn`
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
Labels: enhancement

#1049 Added new Anthropic Sonnet3.5 v2 models
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/anthropic.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/aws.py
Labels: enhancement

#1050 Backport PR #1049 on branch v3-dev (Added new Anthropic Sonnet3.5 v2 models)
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/anthropic.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/aws.py
Labels: enhancement

#1051 Added Developer documentation for streaming responses
  docs/source/developers/index.md
Labels: documentation

#1048 Implement streaming for `/fix`
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/fix.py
Labels: enhancement

#1058 Backport PR #1051 on branch v3-dev (Added Developer documentation for streaming responses)
  docs/source/developers/index.md
Labels: documentation

#1059 Backport PR #1048 on branch v3-dev (Implement streaming for `/fix`)
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/fix.py
Labels: enhancement

#1060 Backport PR #1057 on branch v3-dev ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: maintenance

#1064 Added Ollama to the providers table in user docs
  docs/source/users/index.md
Labels: documentation

#1066 Backport PR #1064 on branch v3-dev (Added Ollama to the providers table in user docs)
  docs/source/users/index.md
Labels: documentation

#1056 Add examples of using Fields and EnvAuthStrategy to developer documentation
  docs/source/developers/index.md
Labels: enhancement

#1073 Backport PR #1056 on branch v3-dev (Add examples of using Fields and EnvAuthStrategy to developer documentation)
  docs/source/developers/index.md
Labels: enhancement

#1069 Merge Anthropic language model providers
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/anthropic.py
Labels: enhancement

#1076 Backport PR #1069 on branch v3-dev (Merge Anthropic language model providers)
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/anthropic.py
Labels: enhancement

#1068 Allow `$` to literally denote quantities of USD in chat
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/src/components/rendermime-markdown.tsx
Labels: bug

#1079 Backport PR #1068 on branch v3-dev (Allow `$` to literally denote quantities of USD in chat)
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/src/components/rendermime-markdown.tsx
Labels: bug
