Repository jupyterlab/jupyter-ai, pull requests merged in 2024-05, with the labels that each got.

#759 Backport PR #758 on branch 1.x (Switch to langchain_community)
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
Labels: bug

#765 Backport PR #764 on branch 1.x (Updated LLM providers to Add New Bedrock Models IDs)
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: enhancement

#742 learn arxiv tex files
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  packages/jupyter-ai/pyproject.toml
Labels: enhancement

#711 Distinguish between completion and chat models
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/base.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/model_mixin.py
  packages/jupyter-ai/jupyter_ai/config/config_schema.json
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/__snapshots__/test_config_manager.ambr
  packages/jupyter-ai/jupyter_ai/tests/completions/test_handlers.py
  packages/jupyter-ai/src/completions/plugin.ts
  packages/jupyter-ai/src/completions/provider.ts
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/settings/use-server-info.ts
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/tokens.ts
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
Labels: enhancement

#768 change unsupported_slash_commands default value from dict to set
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: bug

#771 Backport PR #768 on branch 1.x ( change unsupported_slash_commands default value from dict to set)
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
Labels: bug

#778 Add Titan embedding model v2
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
Labels: enhancement

#779 Backport PR #778 on branch 1.x (Add Titan embedding model v2)
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
Labels: enhancement

#770 Save chat history to Jupyter Lab's root directory
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/chat_handlers/export.py
Labels: bug, enhancement

#784 Updated Hugging Face chat and magics processing with new APIs, clients
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
Labels: bug

#789 Add code toolbar to Jupyter AI chat
  packages/jupyter-ai/src/components/chat.tsx
  packages/jupyter-ai/src/components/code-blocks/code-toolbar.tsx
  packages/jupyter-ai/src/components/code-blocks/copy-button.tsx
  packages/jupyter-ai/src/components/copy-button.tsx
  packages/jupyter-ai/src/components/mui-extras/tooltipped-icon-button.tsx
  packages/jupyter-ai/src/components/rendermime-markdown.tsx
  packages/jupyter-ai/src/contexts/active-cell-context.tsx
  packages/jupyter-ai/src/icons.ts
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/widgets/chat-sidebar.tsx
  packages/jupyter-ai/style/icons/replace-cell.svg
Labels: enhancement

#793 Added gpt-4o
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
Labels: enhancement

#794 Fix Azure OpenAI authentication from UI
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
Labels: bug
