Repository jupyterlab/jupyter-ai, pull requests merged in 2025-01, with the labels that each got.

#1185 Fix specifying empty list in provider and model allow/denylists
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_utils.py
  packages/jupyter-ai-magics/jupyter_ai_magics/utils.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
Labels: bug

#1189 Backport PR #1185 on branch 2.x (Fix specifying empty list in provider and model allow/denylists)
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_utils.py
  packages/jupyter-ai-magics/jupyter_ai_magics/utils.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
Labels: bug

#1188 Fix dev install steps in contributor docs
  docs/source/contributors/index.md
Labels: documentation

#1191 Backport PR #1188 on branch 2.x (Fix dev install steps in contributor docs)
  docs/source/contributors/index.md
Labels: documentation

#1186 Remove remaining shortcut to focus the chat input
  packages/jupyter-ai/schema/plugin.json
Labels: bug

#1193 Update documentation to add usage of `Openrouter`
  docs/source/_static/ai-settings.png
  docs/source/_static/openrouter-chat.png
  docs/source/_static/openrouter-model-setup.png
  docs/source/users/index.md
  docs/source/users/openrouter.md
Labels: documentation

#1195 Backport PR #1193 on branch 2.x (Update documentation to add usage of `Openrouter`)
  docs/source/_static/ai-settings.png
  docs/source/_static/openrouter-chat.png
  docs/source/_static/openrouter-model-setup.png
  docs/source/users/index.md
  docs/source/users/openrouter.md
Labels: documentation

#1199 [2.x] Upgrade to LangChain v0.3 and Pydantic v2
  .github/workflows/lint.yml
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/models/completion.py
  packages/jupyter-ai-magics/jupyter_ai_magics/models/persona.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openrouter.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_base_provider.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_provider_metaclass.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/callback_handlers/metadata.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/base.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/context_providers/base.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/history.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_context_providers.py
  packages/jupyter-ai/jupyter_ai/tests/test_extension.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
  packages/jupyter-ai/pyproject.toml
  pyproject.toml
Labels: enhancement

#1201 Upgrade to LangChain v0.3 and Pydantic v2
  .github/workflows/lint.yml
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/models/completion.py
  packages/jupyter-ai-magics/jupyter_ai_magics/models/persona.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openrouter.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_base_provider.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_provider_metaclass.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/callback_handlers/metadata.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/base.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/context_providers/base.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_extension.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
  packages/jupyter-ai/pyproject.toml
  pyproject.toml
Labels: enhancement

#1204 Update developer docs on Pydantic compatibility
  docs/source/developers/index.md
Labels: documentation

#1206 Backport PR #1204 on branch 2.x (Update developer docs on Pydantic compatibility)
  docs/source/developers/index.md
Labels: documentation

#1202 Fix Amazon Nova support (use `StrOutputParser`)
  docs/source/developers/index.md
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
Labels: bug

#1211 Docs: Update installation steps to work in bash & zsh
  docs/source/users/index.md
Labels: documentation

#1210 Fix MUI theme in Jupyter AI Settings
  packages/jupyter-ai/src/index.ts
  packages/jupyter-ai/src/widgets/settings-widget.tsx
Labels: bug

#1217 Typo in comment
  packages/jupyter-ai-magics/jupyter_ai_magics/models/completion.py
Labels: documentation, maintenance

#1216 Fixes duplicate api key being passed in `openrouter.py`
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openrouter.py
Labels: bug

#1218 Backport PR #1217 on branch 2.x (Typo in comment)
  packages/jupyter-ai-magics/jupyter_ai_magics/models/completion.py
Labels: documentation, maintenance

#1219 Backport PR #1216 on branch 2.x (Fixes duplicate api key being passed in `openrouter.py`)
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openrouter.py
Labels: bug
