Repository jupyterlab/jupyter-ai, pull requests merged in 2025-04, with the labels that each got.

#1298 Updating embeddings config fields from prespecified custom config file
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: bug

#1302 Backport PR #1298 on branch 2.x (Updating embeddings config fields from prespecified custom config file)
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: bug

#1303 Add `default_completions_model` trait
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: bug

#1306 Backport PR #1303 on branch 2.x (Add `default_completions_model` trait)
  docs/source/users/index.md
  packages/jupyter-ai/jupyter_ai/extension.py
Labels: bug

#1309 Open the AI settings in a side panel in Notebook application
  packages/jupyter-ai/package.json
  packages/jupyter-ai/src/index.ts
  yarn.lock
Labels: bug

#1318 Update documentation to show usage with OpenRouter API and URL
  docs/source/_static/openrouter-model-setup-2.png
  docs/source/users/openrouter.md
Labels: documentation

#1319 Backport PR #1318 on branch 2.x (Update documentation to show usage with OpenRouter API and URL)
  docs/source/_static/openrouter-model-setup-2.png
  docs/source/users/openrouter.md
Labels: documentation

#1321 [2.x] Expand edge case handling in ConfigManager
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
Labels: bug

#1322 [3.x] Expand edge case handling in ConfigManager
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
Labels: bug

#1325 Added new `gpt-4.1` models
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
Labels: enhancement

#1330 Handle missing field in config.json on version upgrade
  packages/jupyter-ai/jupyter_ai/config_manager.py
Labels: bug

#1331 Backport PR #1330 on branch 2.x (Handle missing field in config.json on version upgrade)
  packages/jupyter-ai/jupyter_ai/config_manager.py
Labels: bug
