Repository jupyterlab/jupyter-ai, pull requests merged in 2025-07, with the labels that each got.

#1399 Update user message routing rules
  packages/jupyter-ai-test/jupyter_ai_test/debug_persona.py
  packages/jupyter-ai/jupyter_ai/personas/persona_manager.py
Labels: enhancement

#1392 Use `uv`, overhaul dev setup, update contributor docs
  .github/workflows/e2e-tests.yml
  .github/workflows/unit-tests.yml
  .github/workflows/update-snapshots.yml
  dev-environment.yml
  docs/source/contributors/index.md
  nx.json
  package.json
  packages/jupyter-ai-magics/package.json
  packages/jupyter-ai-test/package.json
  packages/jupyter-ai/package.json
  packages/jupyter-ai/ui-tests/README.md
  scripts/ci-setup.sh
  scripts/dev-setup.sh
  scripts/install.sh
Labels: enhancement

#1405 Add `/refresh-personas` command and default persona configurable
  .gitignore
  package.json
  packages/jupyter-ai-magics/package.json
  packages/jupyter-ai-test/package.json
  packages/jupyter-ai/jupyter_ai/personas/base_persona.py
  packages/jupyter-ai/jupyter_ai/personas/persona_awareness.py
  packages/jupyter-ai/jupyter_ai/personas/persona_manager.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/schema/plugin.json
  packages/jupyter-ai/src/chat-command-plugins/file-command.tsx
  packages/jupyter-ai/src/chat-command-plugins/index.ts
  packages/jupyter-ai/src/chat-command-plugins/slash-commands.tsx
  packages/jupyter-ai/src/chat-commands/index.ts
  packages/jupyter-ai/src/index.ts
Labels: enhancement

#1408 Return error message when the completion model is not specified for the Jupyternaut persona
  packages/jupyter-ai/jupyter_ai/personas/jupyternaut/jupyternaut.py
Labels: bug

#1417 Add VertexAI model provider
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/vertexai.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#1423 Run pre-commit
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/vertexai.py
  packages/jupyter-ai/jupyter_ai/config/__init__.py
  packages/jupyter-ai/jupyter_ai/config/config_models.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/personas/base_persona.py
  packages/jupyter-ai/jupyter_ai/personas/jupyternaut/jupyternaut.py
  packages/jupyter-ai/jupyter_ai/personas/persona_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
Labels: maintenance

#1421 Backport PR #1417 on branch 2.x (Add VertexAI model provider)
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/vertexai.py
  packages/jupyter-ai-magics/pyproject.toml
Labels: enhancement

#1425 [litellm] Initial migration to LiteLLM
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_utils.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/model_providers/model_handlers.py
  packages/jupyter-ai/jupyter_ai/model_providers/model_list.py
  packages/jupyter-ai/jupyter_ai/personas/base_persona.py
  packages/jupyter-ai/jupyter_ai/personas/jupyternaut/jupyternaut.py
  packages/jupyter-ai/jupyter_ai/personas/jupyternaut/prompt_template.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/settings/model-id-input.tsx
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/src/widgets/settings-widget.tsx
Labels: enhancement

#1435 [litellm] Remove LangChain from source code
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/_import_utils.py
  packages/jupyter-ai-magics/jupyter_ai_magics/aliases.py
  packages/jupyter-ai-magics/jupyter_ai_magics/base_provider.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/old_help_strings.txt
  packages/jupyter-ai-magics/jupyter_ai_magics/old_prompt_templates.txt
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/anthropic.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/aws.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/cohere.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/gemini.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/mistralai.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/nvidia.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/ollama.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openrouter.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/vertexai.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/py.typed
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_base_provider.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_imports.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_utils.py
  packages/jupyter-ai-magics/jupyter_ai_magics/utils.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/pyproject.toml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/llm.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/provider.py
  packages/jupyter-ai-test/jupyter_ai_test/test_llms.py
  packages/jupyter-ai-test/jupyter_ai_test/test_providers.py
  packages/jupyter-ai-test/pyproject.toml
  packages/jupyter-ai/jupyter_ai/__init__.py
  packages/jupyter-ai/jupyter_ai/completions/completion_prompts.py
  packages/jupyter-ai/jupyter_ai/completions/completion_types.py
  packages/jupyter-ai/jupyter_ai/completions/completion_utils.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/base.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/default.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/model_mixin.py
  packages/jupyter-ai/jupyter_ai/completions/models.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/history.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/personas/jupyternaut/prompt_template.py
  packages/jupyter-ai/jupyter_ai/tests/completions/test_handlers.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_extension.py
  packages/jupyter-ai/src/components/settings/use-server-info.ts
Labels: enhancement

#1439 Implement new Secrets UI and REST API
  .gitignore
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/secrets/secrets_manager.py
  packages/jupyter-ai/jupyter_ai/secrets/secrets_rest_api.py
  packages/jupyter-ai/jupyter_ai/secrets/secrets_types.py
  packages/jupyter-ai/jupyter_ai/secrets/secrets_utils.py
  packages/jupyter-ai/jupyter_ai/secrets/test_secrets_utils.py
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/mui-extras/async-icon-button.tsx
  packages/jupyter-ai/src/components/settings/existing-api-keys.tsx
  packages/jupyter-ai/src/components/settings/secrets-input.tsx
  packages/jupyter-ai/src/components/settings/secrets-list.tsx
  packages/jupyter-ai/src/components/settings/secrets-section.tsx
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/style/chat-settings.css
Labels: enhancement
