Repository jupyterlab/jupyter-ai, pull requests merged in 2025-02, with the labels that each got.

#1222 Backport PR #1167 on branch 2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: maintenance

#1225 Enforce path imports for MUI icons, upgrade to ESLint v8
  packages/jupyter-ai/.eslintrc.js
  packages/jupyter-ai/package.json
  packages/jupyter-ai/src/components/settings/existing-api-keys.tsx
  packages/jupyter-ai/src/slash-autocompletion.tsx
  yarn.lock
Labels: bug

#1226 Backport PR #1225 on branch 2.x (Enforce path imports for MUI icons, upgrade to ESLint v8)
  packages/jupyter-ai/.eslintrc.js
  packages/jupyter-ai/package.json
  packages/jupyter-ai/src/components/chat-input.tsx
  packages/jupyter-ai/src/components/chat-messages/chat-message-delete.tsx
  packages/jupyter-ai/src/components/chat-messages/chat-message-menu.tsx
  packages/jupyter-ai/src/components/settings/existing-api-keys.tsx
  yarn.lock
Labels: bug

#1228 Upgrade to `actions/cache@v4`
  .github/workflows/e2e-tests.yml
Labels: maintenance

#1197 Show error icon near cursor on inline completion errors
  packages/jupyter-ai/jupyter_ai/completions/handlers/base.py
  packages/jupyter-ai/jupyter_ai/tests/completions/test_handlers.py
  packages/jupyter-ai/src/completions/provider.ts
  packages/jupyter-ai/src/completions/types.ts
Labels: enhancement

#1230 Backport PR #1197 on branch 2.x (Show error icon near cursor on inline completion errors)
  packages/jupyter-ai/jupyter_ai/completions/handlers/base.py
  packages/jupyter-ai/jupyter_ai/tests/completions/test_handlers.py
  packages/jupyter-ai/src/completions/provider.ts
  packages/jupyter-ai/src/completions/types.ts
Labels: enhancement

#1224 Update documentation for setting API keys without revealing them
  README.md
  docs/source/users/index.md
  examples/sagemaker.ipynb
Labels: documentation

#1231 Backport PR #1224 on branch 2.x (Update documentation for setting API keys without revealing them)
  README.md
  docs/source/users/index.md
  examples/sagemaker.ipynb
Labels: documentation

#1232 Add documentation for vLLM usage
  docs/source/_static/vllm-aisettings.png
  docs/source/_static/vllm-api.png
  docs/source/_static/vllm-chat.png
  docs/source/_static/vllm-serve.png
  docs/source/users/index.md
  docs/source/users/vllm.md
Labels: documentation

#1233 Backport PR #1232 on branch 2.x (Add documentation for vLLM usage)
  docs/source/_static/vllm-aisettings.png
  docs/source/_static/vllm-api.png
  docs/source/_static/vllm-chat.png
  docs/source/_static/vllm-serve.png
  docs/source/users/index.md
  docs/source/users/vllm.md
Labels: documentation

#1235 Add information about ollama - document it as an available provider and provide clearer troubleshooting help.
  docs/source/users/index.md
Labels: documentation

#1239 Backport PR #1235 on branch 2.x (Add information about ollama - document it as an available provider and provide clearer troubleshooting help.)
  docs/source/users/index.md
Labels: documentation

#1241 Backport PR #1234 on branch 2.x (Remove the dependency on `jupyterlab`)
  packages/jupyter-ai/pyproject.toml
Labels: maintenance

#1254 Fix: Enable up and down arrow keys in chat input
  packages/jupyter-ai/src/components/chat-input.tsx
Labels: bug

#1257 Refactor Chat Handlers to Simplify Initialization
  packages/jupyter-ai/jupyter_ai/__init__.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/__init__.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
Labels: enhancement

#1266 Backport PR #1257 on branch 2.x (Refactor Chat Handlers to Simplify Initialization)
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
Labels: enhancement
