Repository jupyterlab/jupyter-ai, pull requests merged in 2025-06, with the labels that each got.

#1338 Separate `BaseProvider` for faster import
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/_import_utils.py
  packages/jupyter-ai-magics/jupyter_ai_magics/base_provider.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/anthropic.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/aws.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/cohere.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/gemini.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/mistralai.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/nvidia.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/ollama.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openrouter.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_imports.py
  packages/jupyter-ai-magics/jupyter_ai_magics/utils.py
Labels: enhancement

#1361 Fix the path missing in inline completion request when there is no kernel
  packages/jupyter-ai/src/completions/provider.ts
Labels: bug

#1362 Backport PR #1361 on branch 2.x (Fix the path missing in inline completion request when there is no kernel)
  packages/jupyter-ai/src/completions/provider.ts
Labels: bug

#1358 Periodically update the persona awareness to keep it alive
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/utils/streaming.py
  packages/jupyter-ai/jupyter_ai/constants.py
  packages/jupyter-ai/jupyter_ai/personas/base_persona.py
  packages/jupyter-ai/jupyter_ai/personas/persona_awareness.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/pyproject.toml
  yarn.lock
Labels: bug, do-not-port

#1351 Implement stop streaming button in v3
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/personas/base_persona.py
  packages/jupyter-ai/jupyter_ai/personas/persona_manager.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/src/components/message-footer/stop-button.tsx
  packages/jupyter-ai/src/index.ts
  yarn.lock
Labels: enhancement, do-not-port

#1370 Updated documentation for using Ollama with cell magics on non-default port
  docs/source/_static/ollama-settings.png
  docs/source/users/index.md
Labels: documentation

#1369 Remove unused code from v3 `main` branch
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/pyproject.toml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/slash_command.py
  packages/jupyter-ai-test/jupyter_ai_test/test_slash_commands.py
  packages/jupyter-ai-test/pyproject.toml
  packages/jupyter-ai/jupyter_ai/callback_handlers/__init__.py
  packages/jupyter-ai/jupyter_ai/callback_handlers/metadata.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/__init__.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/help.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/utils/streaming.py
  packages/jupyter-ai/jupyter_ai/constants.py
  packages/jupyter-ai/jupyter_ai/context_providers/__init__.py
  packages/jupyter-ai/jupyter_ai/context_providers/base.py
  packages/jupyter-ai/jupyter_ai/context_providers/file.py
  packages/jupyter-ai/jupyter_ai/document_loaders/__init__.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  packages/jupyter-ai/jupyter_ai/document_loaders/splitter.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/static/.hidden_file.pdf
  packages/jupyter-ai/jupyter_ai/tests/static/.hidden_file.txt
  packages/jupyter-ai/jupyter_ai/tests/static/file0.html
  packages/jupyter-ai/jupyter_ai/tests/static/file1.txt
  packages/jupyter-ai/jupyter_ai/tests/static/file2.py
  packages/jupyter-ai/jupyter_ai/tests/static/file3.csv
  packages/jupyter-ai/jupyter_ai/tests/static/file3.xyz
  packages/jupyter-ai/jupyter_ai/tests/static/file4.pdf
  packages/jupyter-ai/jupyter_ai/tests/static/file9.ipynb
  packages/jupyter-ai/jupyter_ai/tests/test_context_providers.py
  packages/jupyter-ai/jupyter_ai/tests/test_directory.py
  packages/jupyter-ai/pyproject.toml
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/style/base.css
  packages/jupyter-ai/style/expandable-text-field.css
Labels: maintenance, do-not-port

#1371 Backport PR #1370 on branch 2.x (Updated documentation for using Ollama with cell magics on non-default port)
  docs/source/_static/ollama-settings.png
  docs/source/users/index.md
Labels: documentation

#1384 Backport PR #1381 on branch 2.x (Refresh the list of supported Gemini models.)
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/gemini.py
Labels: enhancement

#1376 Add functions for finding the .jupyter directory or the workspace directory
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/personas/base_persona.py
  packages/jupyter-ai/jupyter_ai/personas/directories.py
  packages/jupyter-ai/jupyter_ai/personas/persona_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_directories.py
Labels: enhancement, do-not-port

#1382 Added toolkit models
  packages/jupyter-ai/jupyter_ai/tests/test_tools.py
  packages/jupyter-ai/jupyter_ai/tools/__init__.py
  packages/jupyter-ai/jupyter_ai/tools/models.py
Labels: enhancement

#1390 Hide backslashes in `@file` paths with spaces
  packages/jupyter-ai/src/chat-commands/context-commands.tsx
Labels: enhancement

#1380 Load personas dynamically from `.jupyter` dir
  packages/jupyter-ai/jupyter_ai/personas/persona_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_personas.py
Labels: enhancement

#1396 Add ignore globs for hidden files in CM config
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/personas/persona_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_personas.py
Labels: enhancement

#1397 Add error handling for persona loading failures
  packages/jupyter-ai/jupyter_ai/personas/persona_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_personas.py
Labels: enhancement
