Repository jupyterlab/jupyter-ai, pull requests merged in 2025-08, with the labels that each got.

#1446 PR Template
  .github/workflows/pull_request_template.md
Labels: enhancement

#1437 Adding `magics` functionality to the `litellm` implementation
  docs/source/users/index.md
  packages/jupyter-ai-magics/jupyter_ai_magics/__init__.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/old_help_strings.txt
  packages/jupyter-ai-magics/jupyter_ai_magics/old_prompt_templates.txt
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_magics.py
  packages/jupyter-ai/jupyter_ai/__init__.py
  packages/jupyter-ai/jupyter_ai/completions/completion_utils.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/base.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/default.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/secrets/secrets_manager.py
  packages/jupyter-ai/jupyter_ai/secrets/secrets_rest_api.py
  packages/jupyter-ai/jupyter_ai/secrets/secrets_types.py
  packages/jupyter-ai/jupyter_ai/secrets/secrets_utils.py
  packages/jupyter-ai/jupyter_ai/secrets/test_secrets_utils.py
  packages/jupyter-ai/jupyter_ai/tests/completions/test_handlers.py
  packages/jupyter-ai/jupyter_ai/tests/test_extension.py
Labels: enhancement

#1458 Implements arguments for providers and models in `%ai list`
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/parsers.py
Labels: enhancement

#1459 Fix `litellm` branch CI, add `EnvSecretsManager` tests
  .github/workflows/lint.yml
  .github/workflows/unit-tests.yml
  conftest.py
  packages/jupyter-ai-magics/jupyter_ai_magics/magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_magics.py
  packages/jupyter-ai/.prettierignore
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/mcp/mcp_config_loader.py
  packages/jupyter-ai/jupyter_ai/mcp/schema.json
  packages/jupyter-ai/jupyter_ai/secrets/secrets_manager.py
  packages/jupyter-ai/jupyter_ai/secrets/secrets_utils.py
  packages/jupyter-ai/jupyter_ai/secrets/tests/test_secrets_manager.py
  packages/jupyter-ai/jupyter_ai/secrets/tests/test_secrets_utils.py
  packages/jupyter-ai/jupyter_ai/tests/completions/test_handlers.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/src/components/settings/model-fields.tsx
  packages/jupyter-ai/src/components/settings/model-parameters-input.tsx
  packages/jupyter-ai/src/handler.ts
  packages/jupyter-ai/src/index.ts
  pyproject.toml
Labels: maintenance

#1445 [litellm] Display model IDs to match search string
  packages/jupyter-ai/src/components/mui-extras/simple-autocomplete.tsx
  packages/jupyter-ai/src/components/settings/model-id-input.tsx
Labels: bug, enhancement

#1468 Clean up AI settings page
  packages/jupyter-ai/jupyter_ai/model_providers/parameters_rest_api.py
  packages/jupyter-ai/src/components/chat-settings.tsx
Labels: enhancement
