Repository jupyterlab/jupyter-ai, pull requests merged in 2025-05, with the labels that each got.

#1333 Added a local identity provider.
  packages/jupyter-ai/jupyter_ai/auth/identity.py
  packages/jupyter-ai/jupyter_ai/tests/test_identity.py
Labels: bug

#1324 Introduce AI persona framework
  package.json
  packages/jupyter-ai-test/jupyter_ai_test/debug_persona.py
  packages/jupyter-ai-test/pyproject.toml
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/history.py
  packages/jupyter-ai/jupyter_ai/personas/__init__.py
  packages/jupyter-ai/jupyter_ai/personas/base_persona.py
  packages/jupyter-ai/jupyter_ai/personas/jupyternaut/__init__.py
  packages/jupyter-ai/jupyter_ai/personas/jupyternaut/jupyternaut.py
  packages/jupyter-ai/jupyter_ai/personas/jupyternaut/prompt_template.py
  packages/jupyter-ai/jupyter_ai/personas/persona_awareness.py
  packages/jupyter-ai/jupyter_ai/personas/persona_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/pyproject.toml
  yarn.lock
Labels: enhancement

#1334 Backport PR #1333 on branch 2.x (Added a local identity provider.)
  packages/jupyter-ai/jupyter_ai/auth/identity.py
  packages/jupyter-ai/jupyter_ai/tests/test_identity.py
Labels: bug

#1340 Revert "Introduce AI persona framework (#1324)"
  package.json
  packages/jupyter-ai-test/jupyter_ai_test/debug_persona.py
  packages/jupyter-ai-test/pyproject.toml
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/history.py
  packages/jupyter-ai/jupyter_ai/personas/__init__.py
  packages/jupyter-ai/jupyter_ai/personas/base_persona.py
  packages/jupyter-ai/jupyter_ai/personas/jupyternaut/__init__.py
  packages/jupyter-ai/jupyter_ai/personas/jupyternaut/jupyternaut.py
  packages/jupyter-ai/jupyter_ai/personas/jupyternaut/prompt_template.py
  packages/jupyter-ai/jupyter_ai/personas/persona_awareness.py
  packages/jupyter-ai/jupyter_ai/personas/persona_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/pyproject.toml
  yarn.lock
Labels: maintenance

#1341 Introduce AI persona framework
  package.json
  packages/jupyter-ai-test/jupyter_ai_test/debug_persona.py
  packages/jupyter-ai-test/pyproject.toml
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/jupyter_ai/history.py
  packages/jupyter-ai/jupyter_ai/personas/__init__.py
  packages/jupyter-ai/jupyter_ai/personas/base_persona.py
  packages/jupyter-ai/jupyter_ai/personas/jupyternaut/__init__.py
  packages/jupyter-ai/jupyter_ai/personas/jupyternaut/jupyternaut.py
  packages/jupyter-ai/jupyter_ai/personas/jupyternaut/prompt_template.py
  packages/jupyter-ai/jupyter_ai/personas/persona_awareness.py
  packages/jupyter-ai/jupyter_ai/personas/persona_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_handlers.py
  packages/jupyter-ai/package.json
  packages/jupyter-ai/pyproject.toml
  yarn.lock
Labels: enhancement

#1342 Backport PR #1329 on branch 2.x (Add `pyupgrade --py39-plus` and `autoflake` to `pre-commit` config)
  .pre-commit-config.yaml
  packages/jupyter-ai-magics/jupyter_ai_magics/completion_utils.py
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/exception.py
  packages/jupyter-ai-magics/jupyter_ai_magics/models/completion.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/aws.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openrouter.py
  packages/jupyter-ai-magics/jupyter_ai_magics/providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/tests/test_magics.py
  packages/jupyter-ai-magics/jupyter_ai_magics/utils.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/llm.py
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/{{cookiecutter.python_name}}/provider.py
  packages/jupyter-ai-test/jupyter_ai_test/test_llms.py
  packages/jupyter-ai-test/jupyter_ai_test/test_providers.py
  packages/jupyter-ai/jupyter_ai/auth/identity.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/base.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/default.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/export.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/fix.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/generate.py
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
  packages/jupyter-ai/jupyter_ai/completions/handlers/model_mixin.py
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/context_providers/_learned.py
  packages/jupyter-ai/jupyter_ai/context_providers/base.py
  packages/jupyter-ai/jupyter_ai/context_providers/file.py
  packages/jupyter-ai/jupyter_ai/document_loaders/directory.py
  packages/jupyter-ai/jupyter_ai/document_loaders/splitter.py
  packages/jupyter-ai/jupyter_ai/handlers.py
  packages/jupyter-ai/jupyter_ai/history.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/static/file2.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_directory.py
Labels: maintenance
