Repository jupyterlab/jupyter-ai, pull requests merged in 2025-03, with the labels that each got.

#1268 Allow chat handlers to be initialized in any order
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
Labels: enhancement

#1269 Backport PR #1268 on branch 2.x (Allow chat handlers to be initialized in any order)
  packages/jupyter-ai/jupyter_ai/chat_handlers/ask.py
Labels: enhancement

#1249 Make Native Chat Handlers Overridable via Entry Points
  docs/source/developers/index.md
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/pyproject.toml
Labels: enhancement

#1274 Backport PR #1249 on branch 2.x (Make Native Chat Handlers Overridable via Entry Points)
  docs/source/developers/index.md
  packages/jupyter-ai/jupyter_ai/extension.py
  packages/jupyter-ai/pyproject.toml
Labels: enhancement

#1272 Correct minimum versions in dependency version ranges
  README.md
  docs/source/users/index.md
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/README.md
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/pyproject.toml
  packages/jupyter-ai-test/README.md
  packages/jupyter-ai-test/pyproject.toml
  packages/jupyter-ai/pyproject.toml
Labels: bug, maintenance, scope:dependencies

#1275 Backport PR #1272 on branch 2.x (Correct minimum versions in dependency version ranges)
  README.md
  docs/source/users/index.md
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/README.md
  packages/jupyter-ai-module-cookiecutter/{{cookiecutter.root_dir_name}}/pyproject.toml
  packages/jupyter-ai-test/README.md
  packages/jupyter-ai-test/pyproject.toml
  packages/jupyter-ai/pyproject.toml
Labels: bug, maintenance, scope:dependencies

#1264 Allow embedding model fields, fix coupled model fields, add custom OpenAI provider
  docs/source/_static/openai-chat-deepseek.png
  docs/source/_static/openai-chat-openai.png
  docs/source/_static/openai-chat-vllm.png
  docs/source/_static/openai-embeddings.png
  docs/source/users/index.md
  docs/source/users/openrouter.md
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/ollama.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/config/config_schema.json
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/__snapshots__/test_config_manager.ambr
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/settings/use-server-info.ts
  packages/jupyter-ai/src/handler.ts
Labels: bug, enhancement

#1282 Backport PR #1264 on branch 2.x (Allow embedding model fields, fix coupled model fields, add custom OpenAI provider)
  docs/source/_static/openai-chat-deepseek.png
  docs/source/_static/openai-chat-openai.png
  docs/source/_static/openai-chat-vllm.png
  docs/source/_static/openai-embeddings.png
  docs/source/users/index.md
  docs/source/users/openrouter.md
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/ollama.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
  packages/jupyter-ai-magics/pyproject.toml
  packages/jupyter-ai/jupyter_ai/config/config_schema.json
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/models.py
  packages/jupyter-ai/jupyter_ai/tests/__snapshots__/test_config_manager.ambr
  packages/jupyter-ai/src/components/chat-settings.tsx
  packages/jupyter-ai/src/components/settings/use-server-info.ts
  packages/jupyter-ai/src/handler.ts
Labels: bug, enhancement

#1280 Ensure magics package version is consistent in future releases
  .jupyter-releaser.toml
  packages/jupyter-ai-magics/pyproject.toml
  scripts/bump-version.py
  scripts/bump-version.sh
Labels: bug, maintenance

#1284 Backport PR #1280 on branch 2.x (Ensure magics package version is consistent in future releases)
  .jupyter-releaser.toml
  packages/jupyter-ai-magics/pyproject.toml
  scripts/bump-version.py
  scripts/bump-version.sh
Labels: bug, maintenance

#1289 Backport PR #1287 on branch 2.x (Remove error log emitted when FAISS file is absent)
  packages/jupyter-ai/jupyter_ai/chat_handlers/learn.py
Labels: bug

#1292 Backport PR #1288 on branch 2.x (Added help text fields for embedding providers in the AI Setting page)
  packages/jupyter-ai-magics/jupyter_ai_magics/embedding_providers.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/ollama.py
  packages/jupyter-ai-magics/jupyter_ai_magics/partner_providers/openai.py
  packages/jupyter-ai/jupyter_ai/handlers.py
Labels: enhancement

#1294 Migrate old config schemas, fix v2.31.0 regression
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
Labels: bug

#1295 Backport PR #1294 on branch 2.x (Migrate old config schemas, fix v2.31.0 regression)
  packages/jupyter-ai/jupyter_ai/config_manager.py
  packages/jupyter-ai/jupyter_ai/tests/test_config_manager.py
Labels: bug
